### ISSUE TITLE
should there be a iter parameter in mkgraph.sh ?

### ISSUE THREAD

**Issue by vince62s** [kaldi-asr/kaldi#1001]
Since we have the possibility to specify an --iter in decode.sh to use some intermediary models, shouldn't there be a similar option for mkgraph.sh to build a graph with the same intermediary model ?

Also, in some instance final.mdl is not ready yet when you want to decode with such an intermediary model.

Just asking.

**Comment by danpovey** [comment]
I think it might be easiest to have 'mkgraph.sh' look for final.mdl if it
exists and is newer than the tree, and otherwise the highest-numbered model
that it can find in that directory that's newer than the tree.  That will
make things easiest.   It can print out what it's using if it doesn't use
final.mdl.
In general it won't make a difference which model is used as the
transition-model does not change during training.
If you have time to prepare a PR for this, it would be great.

Dan

**Comment by vince62s** [comment]
Under a "standard" workflow I agree, but when you go back and forth with various config in a fine tuning operation it's a little tricky.
The beauty of the --iter parameter is that you can specify whatever nale you give to some intermediary saved model of certain configurations. But at times one (well I) may forget to refresh the graph to the right config.

**Comment by danpovey** [comment]
None of the current recipes actually train the transitions in the
intermediate iteration.  So it doesn't actually matter which of the models
you choose-- as long as it corresponds to the correct tree.
Dan

**Comment by vince62s** [comment]
ok understood.
