### ISSUE TITLE
Cuda compilation problem

### ISSUE THREAD

**Issue by alexnanchen** [kaldi-asr/kaldi#1214]
Hello,

When compiling Kaldi, the following error happens on target "nnet3bin":
-------------------------------------------------------------
chain-kernels.cu(25): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (BaseFloat *, BaseFloat)
          detected during:
            instantiation of "void atomic_add(Real *, Real) [with Real=BaseFloat]" 
(55): here
            instantiation of "void atomic_add_thresholded(Real *, Real) [with Real=BaseFloat]" 
(220): here

1 error detected in the compilation of "/tmp/tmpxft_00003300_00000000-19_chain-kernels.compute_13.cpp1.ii".
-------------------------------------------------------------

The OS is debian Jessie. The Nvidia toolkit: nvidia-cuda-toolkit 6.0.37-5 and  the nvcc compiler:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2013 NVIDIA Corporation
Built on Thu_Mar_13_11:58:58_PDT_2014
Cuda compilation tools, release 6.0, V6.0.1

Any ideas that could help?

Many thanks!

Alexandre Nanchen

**Comment by danpovey** [comment]
Are you compiling with double precision (-DKALDI_DOUBLE_PRECISION=1 in
kaldi.mk)?  If so, that would only be supported by a much newer CUDA
toolkit.
Dan

**Comment by alexnanchen** [comment]
KALDI_DOUBLEPRECISION is set to 0.

#$ gcc -D__CUDA_ARCH__=500 -E -x c++ -DCUDA_DOUBLE_MATH_FUNCTIONS  -D__CUDACC__ -D__NVCC__  -fPIC -I"/usr/lib/nvidia-cuda-toolkit/include" -I"../" -I/usr/lib/nvidia-cuda-toolkit/include   -D"HAVE_CUDA" -D"KALDI_DOUBLEPRECISION=0" -include "cuda_runtime.h" -m64 -g -gdwarf-2 -o "/tmp/tmpxft_00006f11_00000000-18_chain-kernels.compute_50.cpp1.ii" "chain-kernels.cu"

**Comment by danpovey** [comment]
You will be able to resolve this problem by uninstalling the
nvidia-cuda-toolkit from aptitude, and instead installing a newer version
from NVidia's download page-- search on Google.
Meanwhile, I'll try to look into exactly at what toolkit version atomicAdd
was added, and update the configure script (NVidia's web page is not very
helpful about when things were added).

**Comment by danpovey** [comment]
@kangshiyin, since you are our de facto CUDA expert, can I ask you to look into this?
The issue is as follows:

  - Firstly, try to figure out from what version of the CUDA toolkit the function atomicAdd has been supported, and in the src/configure script, if nvcc is detected, check the version and fail if the version is less than that with an error like the following:
  "Kaldi no longer supports versions of the NVidia CUDA toolkit less than 6.5; please install a newer version or configure with --use-cuda=no (this will disable the use of GPU)"

 - Next (and this doesn't have to be in the same PR), we need to have better support for configuring with double-precision BaseFloat and running on older hardware.  AtomicAdd [with BaseFloat]  is only used in chain/chain-kernels.cu.  Above that code, you could put the code located at https://docs.nvidia.com/cuda/cuda-c-programming-guide/#atomic-functions that defines double-precision atomicAdd for you in case the CUDA compute capability is too low.   Try to compile Kaldi with double-precision on.  There may be other compilation errors too-- I'm not sure that we've tested that for a while.

BTW, we have only required the atomicAdd function since the chain training was implemented.  Previously I was trying to avoid it, but I think it does make a difference for performance.

**Comment by kangshiyin** [comment]
I just checked the CUDA 5.5 programming guide. AtomicAdd on floating point numbers is a Compute-Capability-dependent feature, rather than CUDA-version-dependent. AtomicAdd on `float` since CC2.x, and atomicAdd on `double` is supported since CC6.0.

I guess @alexnanchen is using CC1.x device. That's why he is using old CUDA 6.0, as newer CUDA does not support CC1.x device anymore.

I will try `KALDI_DOUBLE_PRECISION=1` later on both CC2.0 and CC3.5 devices with CUDA7.5 to see if the current code in `chain-kernels.cu`.

**Comment by danpovey** [comment]
But the compilation process doesn't actually check what the hardware is, it
just requests compilation for a bunch of CUDA_ARCH values that depend only
on the toolkit version (see the "configure" script).  So I don't think he
would have got a compile-time error due to the hardware version (unless he
manually changed the Makefile).

**Comment by alexnanchen** [comment]
No manual changes where done. Just a git clone and make.

**Comment by danpovey** [comment]
I think I see the reason.  The 'configure' script adds pre-2.0 compute
capabilities to the list of things to compile, if CUDA_ARCH is 6.0 or
earlier.
I'll remove that.

**Comment by kangshiyin** [comment]
I see what you mean. I think removing support for CC1.3 devices is a good choice.

**Comment by alexnanchen** [comment]
Removing pre-2.0 support in configure file solve the compilation problem.

Many thanks for this quick answer and great toolkit!!

**Comment by DAVID-Hown** [comment]
Hello, I have also encountered the same problem. This error occurred when I was running other people's demo examples. This problem has bothered me for many days.
error：
Number of threads used: 32
Loading models parameters...
./models/trained/disparity-estimation-no-mask.tar
Model disparity loaded succesfully.
./models/trained/disparity-refinement.tar
Model refine loaded succesfully.
./models/trained/inpainting-color.tar
Model inpaint loaded succesfully.
Traceback (most recent call last):
File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 681, in compile
nvrtc.compileProgram(self.ptr, options)
File "cupy_backends/cuda/libs/nvrtc.pyx", line 139, in cupy_backends.cuda.libs.nvrtc.compileProgram
File "cupy_backends/cuda/libs/nvrtc.pyx", line 151, in cupy_backends.cuda.libs.nvrtc.compileProgram
File "cupy_backends/cuda/libs/nvrtc.pyx", line 67, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/DATA/jupyter/share/haodawei/improved-kbe/kbe.py", line 182, in
ken_burn_pipe((tensorImage+1)/2, zoom_settings, output_path, pretrained_estim=pretrained_estim)
File "/DATA/jupyter/share/haodawei/improved-kbe/utils/pipeline.py", line 112, in call
numpyResult = process_kenburns({
File "/DATA/jupyter/share/haodawei/improved-kbe/utils/common.py", line 208, in process_kenburns
tensorRender, tensorExisting = render_pointcloud(objectCommon['tensorInpaPoints'] + tensorShift,
File "/DATA/jupyter/share/haodawei/improved-kbe/utils/common.py", line 435, in render_pointcloud
launch_kernel('kernel_pointrender_updateZee', preprocess_kernel('''
File "cupy/_util.pyx", line 67, in cupy._util.memoize.decorator.ret
File "/DATA/jupyter/share/haodawei/improved-kbe/utils/common.py", line 380, in launch_kernel
return cupy.cuda.compile_with_cache(strKernel, tuple([ '-I ' + os.environ['CUDA_HOME'], '-I ' + os.environ['CUDA_HOME'] + '/include' ])).get_function(strFunction)
File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 460, in compile_with_cache
return _compile_module_with_cache(*args, **kwargs)
File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 488, in _compile_module_with_cache
return _compile_with_cache_cuda(
File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 566, in _compile_with_cache_cuda
ptx, mapping = compile_using_nvrtc(
File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 317, in compile_using_nvrtc
return _compile(source, options, cu_path,
File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 301, in _compile
compiled_obj, mapping = prog.compile(options, log_stream)
File "/usr/local/python39/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 698, in compile
raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: /tmp/tmpl94lnfh3/6335edf91d36e122532b0e6f44001e82f777db6a.cubin.cu(2): catastrophic error: cannot open source file "/home/s182169/Master_thesis/GAN-Burns-effect/utils/helper_math.h"

1 catastrophic error detected in the compilation of "/tmp/tmpl94lnfh3/6335edf91d36e122532b0e6f44001e82f777db6a.cubin.cu".
Compilation terminated.
————————————————
my env:
OS : Linux-4.9.0-8-amd64-x86_64-with-glibc2.27
Python Version : 3.9.2
CuPy Version : 10.1.0
CuPy Platform : NVIDIA CUDA
NumPy Version : 1.20.1
SciPy Version : 1.6.1
Cython Build Version : 0.29.24
Cython Runtime Version : None
CUDA Root : /usr/local/cuda
nvcc PATH : /usr/local/cuda/bin/nvcc
CUDA Build Version : 10020
CUDA Driver Version : 10020
CUDA Runtime Version : 10020
cuBLAS Version : 10203
cuFFT Version : 10102
cuRAND Version : 10102
cuSOLVER Version : (10, 3, 0)
cuSPARSE Version : 10301
NVRTC Version : (10, 2)
Thrust Version : 100907
CUB Build Version : 100800
Jitify Build Version : 60e9e72
cuDNN Build Version : 8300
cuDNN Version : 8101
NCCL Build Version : 21104
NCCL Runtime Version : 2804
cuTENSOR Version : None
cuSPARSELt Build Version : None
Device 0 Name : Tesla V100-SXM2-32GB
Device 0 Compute Capability : 70
Device 0 PCI Bus ID : 0000:18:00.0
Device 1 Name : Tesla V100-SXM2-32GB
Device 1 Compute Capability : 70
Device 1 PCI Bus ID : 0000:3B:00.0
Device 2 Name : Tesla V100-SXM2-32GB
Device 2 Compute Capability : 70
Device 2 PCI Bus ID : 0000:AF:00.0
