### ISSUE TITLE
More informative errors in python scripts and an Exceptions library.

### ISSUE THREAD

**Issue by vimalmanohar** [kaldi-asr/kaldi#1227]
The python scripts in kaldi currently have an exception called KaldiCommandException when a kaldi command fails and a generic Exception is raised for all other types of errors. We can have more informative errors by defining separate Exception types for different cases and store them in steps/libs/exceptions.py. 

Exception that will be useful for current python scripts are:
1. InputError - When a line read from a file has an invalid format
2. KeyNotUniqueError - When there are duplicates when reading dictionary type objects
3. ArgumentError - When invalid sets of parameters are passed to a python script.

When running jobs, the produced log files can be parsed to see what type of error is. So we can have 
1. DiskError
2. SegmentationFault
and so on, which will be raised by the run_kaldi_command() or run_job() or the background process handler.

@vijayaditya may have some comments regarding the structure of the exceptions library or what exceptions must be added.

**Comment by danpovey** [comment]
I'm a bit skeptical about the use of this...
generally speaking, the exception will have a message that says what it's
about, and generally speaking, the program will just die when there is an
exception.  Unless we need to take a different type of action as a result
of a particular kind of exception, I see no reason to create separate
exception types.  To my mind, it just makes the code harder to understand
and maintain.

I can see that DiskError might be possibly useful, to re-run jobs that
failed because a disk was dead.  But to figure that out from what's in the
log would be extremely difficult.  And I wonder whether the right place to
put that logic would be queue.pl.

**Comment by danpovey** [comment]
Closing this issue, you can re-open if you have more comments.
