### ISSUE TITLE
questions about chime3 in egs

### ISSUE THREAD

**Issue by cxy19941228** [kaldi-asr/kaldi#1232]
recently,I have being learning about speech speration.so I am concentrating on chime4,but the download package in chime4 after unziped is titled as chime3,and the data is not fully downloaded for there is some data needed a password.In the first,I thought maybe i can run the baseline with some data lost.But there is some error which I am still not fully sure is arised by the lose of data.is there someone who have already use the chime4 and is wiling to help me.
the error(the last two sentences) is below:
steps/make_mfcc.sh --nj 8 --cmd run.pl data/dt05_real_noisy exp/make_mfcc/dt05_real_noisy mfcc
utils/validate_data_dir.sh: Successfully validated data-directory data/dt05_real_noisy
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
Succeeded creating MFCC features for dt05_real_noisy
steps/compute_cmvn_stats.sh data/dt05_real_noisy exp/make_mfcc/dt05_real_noisy mfcc
Succeeded creating CMVN stats for dt05_real_noisy
steps/make_mfcc.sh --nj 8 --cmd run.pl data/et05_real_noisy exp/make_mfcc/et05_real_noisy mfcc
utils/validate_data_dir.sh: empty file spk2utt

**Comment by danpovey** [comment]
The chime4 setup is supposed to use chime3 data, only the terms of the
competition were different.
Shinji Watanabe (cc'd) knows more about this setup.
I don't know which data  you could not download... I'm not super familiar
with that setup.

**Comment by merlspeech** [comment]
First, CHiME-3 and CHiME-4 use the same data (but limit the use of data for each task), and we titled chime3 even for CHiME-4 data. So, the data you downloaded is correct.

Second, we actually use LDC WSJ0 data to have more training data, which you need a password. If your institute has the LDC WSJ0 license, you can obtain the password. Please send email to chimechallenge@gmail.com, then we can respond it. If you don't include them, the performance is really bad due to the small amount of training data. We also did not maintain the recipe working without LDC WSJ0 data due to the reason. If you really need it, I could work on that, but again it would not provide the sufficient performance, and I don't think it is necessary right now (I used to work on that, but stopped it with that reason).

If you have any questions about CHiME-3 or CHiME-4, feel free to ask me via chimechallenge@gmail.com
