### ISSUE TITLE
Tune setups with new fast-lstm layer

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1237]
@GaofengCheng, it would be great if you could help with this.

This would be changes on top of the fast_lstm branch-- I hope to merge the fast_lstm branch very soon to master.
The issue is this:
  Vijay has recently been doing some experiments with combining TDNN and LSTM that were quite successful.  He has those on Switchboard.  I have been testing the fast_lstm stuff on tedlium s5_r2, with the chain models (since they're faster to train).  I only did one experiment with the TDNN+LSTM, you can see it in that PR as egs/tedlium/s5_r2/local/chain/tuning/tdnn_lstm_1a.sh.  It's doing very well.  I'm wondering if we can get similar results with fewer TDNN layers, since I do care about decoding speed.  In any case, that setup isn't tuned at all.  
Another issue is that we need to test the fast-lstm code on Switchboard-- I want this to be done before I merge the branch to master, to make sure the results are not worse for some reason.  You can basically just copy one of Vijay's previous experiments and modify lstmp-layer -> fast-lstmp-layer in the xconfig.
Vijay will start at Google next Monday and is traveling right now, so he will likely have very limited time to do anything about this.

**Comment by GaofengCheng** [comment]
@danpovey OK, I will help this. I don't have the tedlium data...., the first issue I can do no help......I will merge kaldi/master and kaldi/lstm-fast locally,  help the second issue....

**Comment by danpovey** [comment]
the tedlium data is free to download.

**Comment by GaofengCheng** [comment]
@danpovey hm...got it

**Comment by GaofengCheng** [comment]
![image](https://cloud.githubusercontent.com/assets/7532101/20834796/0c470962-b8d2-11e6-80d5-cd3abdc6b597.png)
@danpovey

**Comment by vijayaditya** [comment]
A good way to check the behavior of the two models is to check their
log-probability plots. Could you please provide them for the two tdnn-lstm
models ?

Another thing : as Dan would like a faster model I would recommend reducing
tdnn output-dims rather than the number of tdnn layers. We usually do
single CPU decoding and this would give us similar speed improvements.

Vijay

**Comment by danpovey** [comment]
That's great.  Can you please make a PR for this right away?
Dan

**Comment by GaofengCheng** [comment]
![default](https://cloud.githubusercontent.com/assets/7532101/20855478/5a8d7398-b938-11e6-811d-d362edb9add6.JPG)
@vijayaditya

**Comment by vdp** [comment]
BTW Dan, you say:
>  I'm wondering if we can get similar results with fewer TDNN layers, since I do care about decoding speed

Does this mean that the TDNN layers are slower than the LSTM ones? I was under impression that the recursive models are inherently slower, because we can't batch activations together, so we can't take full advantage of the optimizations for the BLAS GEMM operations..

(And BTW congrats to @vijayaditya for the new job. It's a great place to do speech recognition work I'd imagine. As a fan of the Kaldi project, thank you for all the contributions you've made to the project)

**Comment by danpovey** [comment]
No, TDNN layers are fast.. but there are so many of them.

Hopefully Vijay will not be *completely* gone... Michiel told me that it's
OK to contribute to open source as long as it doesn't take an unreasonable
amount of time.

**Comment by vdp** [comment]
Ah I see, thanks!
And great to hear that Vijay may remain active on the Kaldi front.

**Comment by vince62s** [comment]
unrelated, but is there an existing script / app to plot the log-prob like this or do I have to grab all the log files and redo it ?
thanks.

**Comment by danpovey** [comment]
See
steps/nnet3/report/generate_plots.py

**Comment by danpovey** [comment]
Closing this issue as it's done.
