### ISSUE TITLE
Sticky posts for the kaldi help mailing list

### ISSUE THREAD

**Issue by vince62s** [kaldi-asr/kaldi#1292]
Dan,
I am not sure whether you contemplated this before, but you are very very patient and sometimes not :)
when answering the kaldi help questions.

I am pretty sure that a sort of FAQ as "sticky posts" may help a lot to avoid newbies questions. Or even a sticky post pointing to the documentation may be good.

If you prefer the current way, fine just close this.
cheers.

**Comment by danpovey** [comment]
I'm afraid I don't have much time to create any extensive content right
now.  There is an issue to add documentation for "decoding with just one
file" which is a common question.

What I was considering is putting a warning that people should make sure
that they have fully read and understood the response to the best of their
ability before posting follow-up questions.  Very often I reply of the form
"see if X; if not, look into Y or Z", and the person tries X and asks a
followup question before looking at the rest of the answer.

Sometimes I regret getting upset at people, but I think there is a real
benefit in scaring away the people who are really very inexperienced with
computers.  They take up a lot of my time spent answering questions but
produce no benefit for the project, and very little for its impact (since
often they will give up eventually, having failed to accomplish anything).

**Comment by danpovey** [comment]
have added a warning a forums.html... closing the issue as it's too generic.
