### ISSUE TITLE
"No fst for utterance" if --map-oov is empty in steps/nnet/align.sh

### ISSUE THREAD

**Issue by pstanisl** [kaldi-asr/kaldi#1427]
Unable to finish `align.sh` if `oov.int` is empty.

`align.sh` runs `sym2int.pl` with argument `--map-oov` and it must be non-empty otherwise the script dies.

```bash
# Map oovs in reference transcription,
oov=`cat $lang/oov.int` || exit 1;
[ -z "$text" ] && text=$sdata/JOB/text
tra="ark:utils/sym2int.pl --map-oov \"$oov\" -f 2- $lang/words.txt $text |";
```

In case `oov.int` is empty it cause "broken-pipe" for `compile-train-graphs` in `align.sh` and warning `No fst for utterance` for every utterance in input data.

A possible solution:
Checking variable `oov` and not to use `--map-oov` if it is empty.

**Comment by danpovey** [comment]
If oov.int was empty then the lang directory would not pass validate_lang.pl, since we require it to be nonempty.  You can just choose an arbitrary word for the OOV symbol if it's not applicable in your setup.  Closing this because I don't think changing this script is the right solution (the same issue would pop up elsewhere, most likely).
