### ISSUE TITLE
Huge memory consumption and slow decoding on Windows (online2-gmm)

### ISSUE THREAD

**Issue by vbearn** [kaldi-asr/kaldi#1484]
Hi,

We have been using Kaldi on linux for sometime now. Due to some project needs we need to have the decoding modules on Windows.

I have successfully compiled Kaldi with MKL support and I am trying to use online2-wav-gmm-latgen-faster sample with one of our previously trained models (based on Persian "Farsdat" )

Loading the HCLG in Kaldi currently consumes around 17GB of RAM on Linux Ubuntu 14.04 and its decoding speed is 1:1 (decoding time is the same as wav file length), but **that exact model consumes around 64GB of RAM in windows** and the decoding speed is around 1:10 (ten times the length of wave).

I have read other threads on memory issues but haven't been able to gather the information that would guide me to solve the problem.

My configuration is as follows:

- Kaldi Version 5.0 (hash: 21cfe99)
- Visual Studio 2013 + OpenFST v1.3.4 + Intel MKL 2017 + No CUDA
- Memory consumed is around 64GB (consumed in ReadFstKaldi method) for a 130K tri3 graph, beam=10.0 lattice-beam=6.0 acoustic-scale=0.072
- sizeof BaseFloat is 4 bytes (typedef float   BaseFloat;)

Could you please point me to some extra tests/debuggings that would be helpful to further identify the issue?

**Comment by danpovey** [comment]
I assume you mean a 130M graph.  
I've created a separate issue to look into whether we can read graphs as ConstFst instead of VectorFst, to reduce memory consumption in graph loading.  That should help with this problem.
I really can't help you about debugging methods because I'm not familiar with debugging procedures on Windows, only on linux.  It could be that Windows' implementation of stl vector is a bit bloated, or its memory management is less efficient than linux.
for questions like this, please see kaldi-asr.org/forums.html for how to ask questions.
