### ISSUE TITLE
Failed to load shared library

### ISSUE THREAD

**Issue by sinha135** [kaldi-asr/kaldi#1634]
Error Loading shared library 

#online2-wav-nnet3-latgen-faster: error while loading shared libraries: libfst.so.7: cannot open shared #object file: No such file or directory
 Accounting: time=0 threads=1
Ended (code 127) at Fri May 19 11:12:46 IST 2017, elapsed time 0 seconds

No idea where to get this libsft from

**Comment by danpovey** [comment]
You get this error  when you compile Kaldi in one place and then move the directory tree around, because the location of the library path is encoded in the binary.
Fixes are: move it back, patch it with a soft link, or add the location to your LD_LIBRARY_PATH.  Best to find someone local with more Linux experience to help you, I'm busy.
