### ISSUE TITLE
Transcription contents for CSJ

### ISSUE THREAD

**Issue by homink** [kaldi-asr/kaldi#1901]
Hello,

I just ran CSJ recipe and found that transcription includes such POS (Part-of-Speech) per token. Such transcription text has been used for training as well as language model building. This looks weird because transcription should be in a form of such spoken text. . Could anyone help me understand how this is working?

head -n 2 data/local/train/text
A01F0019_0000136_0014199  えー+感動詞 この+連体詞 題名+名詞 から+助詞/格助詞 私+代名詞 が+助詞/格助詞 何+代名詞 を+助詞/格助詞 やり+動詞/ラ行五段/連用形 たい+助動詞/終止形 か+助詞/終助詞 って+助詞/副助詞 いう+動詞/ワア行五段/連体形 の+助詞/準体助詞 が+助詞/格助詞 ちょっと+副詞 分かり+動詞/ラ行五段/連用形 づらい+接尾辞/形容詞型/終止形 と+助詞/格助詞 思う+動詞/ワア行五段/連体形 ん+助詞/準体助詞 です+助動詞/終止形 けれど+助詞/接続助詞 も+助詞/副助詞 <sp> えー+感動詞 この+連体詞 研究+名詞 を+助詞/格助詞 通し+動詞/サ行五段/連用形 て+助詞/接続助詞 私+代名詞 が+助詞/格助詞 やり+動詞/ラ行五段/連用形 たかっ+助動詞/連用形/促音便 た+助動詞/連体形 こと+名詞 と+助詞/格助詞 いう+動詞/ワア行五段/連体形 の+助詞/準体助詞 は+助詞/係助詞 <sp> えーと+感動詞 音声+名詞 と+助詞/格助詞 文字+名詞 と+助詞/格助詞 発話+名詞 運動+名詞 の+助詞/格助詞 と+助詞/格助詞 の+助詞/格助詞 関係+名詞 を+助詞/格助詞 明らか+形状詞 に+助動詞/連用形 する+動詞/サ行変格/連体形 こと+名詞 です+助動詞/終止形
A01F0019_0014601_0026264  えー+感動詞 私+代名詞 共+接尾辞 が+助詞/格助詞 音声+名詞 を+助詞/格助詞 聞き+動詞/カ行五段/連用形 発話+名詞 する+動詞/サ行変格/終止形 また+接続詞 は+助詞/係助詞 文字+名詞 を+助詞/格助詞 読ん+動詞/マ行五段/連用形/撥音便 で+助詞/接続助詞 発話+名詞 する+動詞/サ行変格/終止形 って+助詞/副助詞 いう+動詞/ワア行五段/連体形 こと+名詞 は+助詞/係助詞 私+代名詞 共+接尾辞 が+助詞/格助詞 <sp> 人間+名詞 が+助詞/格助詞 日常+名詞 的+接尾辞 に+助動詞/連用形 行なっ+動詞/ワア行五段/連用形/促音便 て+助詞/接続助詞 いる+動詞/ア行上一段/連体形 こと+名詞 で+助動詞/連用形 あり+動詞/ラ行五段/連用形 ます+助動詞/終止形 し+助詞/接続助詞 <sp> ま+感動詞 人間+名詞 の+助詞/格助詞 言語+名詞 生活+名詞 言語+名詞 の+助詞/格助詞 う+言いよどみ

**Comment by danpovey** [comment]
Shinji, can you comment?


2017-09-22 1:50 GMT-04:00 homink <notifications@github.com>:

**Comment by jtrmal** [comment]
I think Shinji is @sw005320

**Comment by sw005320** [comment]
This is a quite standard way for the Japanese speech recognition since Japanese has a lot of words  especially hiragana have the same graphemes but have different meanings, and it can be distinguished by POS (e.g., する+動詞/サ行変格/連体形 and する+動詞/サ行変格/終止形). Standard Japanese ASR acoustic and language models are trained based on this form (we first process morphological analyzer and get this form, and regarding it as a different word). It's more-like a convention, and If you want to write the paper, I recommend you to use this word+POS representation to compare the "word" (again word with POS) error rate number with the other report. If you just want to simply build a Japanese system, you may disregard this type of information, and just use the first field delimited by "+".

**Comment by homink** [comment]
Dear @sw005320 

Thanks for your reply. It make sense to disambiguate such Japanese words in terms of written context. For further understanding, could you let me know how this convention would be useful to train acoustic model? In my inexperienced view, the trained acoustic model would perform similar for with/without POS tag because speech signal itself is still ambiguous. Such N-gram LM could disambiguate homonym word utterance in a phrase or full sentence.

**Comment by sw005320** [comment]
You're right. POS tag itself does not change the pronunciation and the above discussion only applies to language model, and not acoustic model. I have to collect what I said. BTW, the pronunciation in Japanese highly depends on the POS, and a Japanese morphological analyzer solves tokenization, POS tagging and pronunciation labelling at the same time. Thus, to obtain the pronunciation for acoustic model training, we still use a Japanese morphological analyze first.
