### ISSUE TITLE
Why this less operation result fliped?

### ISSUE THREAD

**Issue by zh794390558** [kaldi-asr/kaldi#1963]
https://github.com/kaldi-asr/kaldi/blob/85a3dd5f0b71e419abf1169a26b759bfc423a543/src/decoder/simple-decoder.h#L116

Maybe below is correct and make sense:
`    bool operator < (const Token &other) {
      return cost_ < other.cost_;
    }
`

**Comment by jtrmal** [comment]
probably because of the fact that the cost will be -logprob, but you want
to keep the ordering in the probability sense.
y.

**Comment by zh794390558** [comment]
@jtrmal  You mean the wfst' weight is always negative in kaldi ? or wfst' weight type is 'log' not 'tropical'?

**Comment by danpovey** [comment]
The fact that it's called 'cost' implies that it's of the larger-is-worse variety, like -logprob.
And without looking at the code that requires that operator you can't reason about which way is correct.
Anyway this is not the place for questions of this type, see kaldi-asr.org/forums.html (but I encourage you to just read the code more carefully rather than ask there).

**Comment by zh794390558** [comment]
@danpovey If you use 'cost' as the variable name, then it means larger is worse.  So the code must be  `if ( *(find_iter->second) > *new_tok )`,  not this one: `if ( *(find_iter->second) < *new_tok )`.
