### ISSUE TITLE
while iam training online decoding iam getting  error

### ISSUE THREAD

**Issue by iithgkb** [kaldi-asr/kaldi#1996]
iam using steps/nnet2/train_pnorm_simple2.sh....iam getting following error.... 

ERROR (nnet-combine-fast[5.2.158~1-e3fb7]:ExpectToken():io-funcs.cc:197) Failed to read token [started at file position -1], expected <TransitionModel>

iam new to kaldi...please help me

**Comment by danpovey** [comment]
That is a very generic error, it happens when one of the inputs is not there.  So hard to know without more context.   You should ask on the forums for things like this (see kaldi-asr.org/forums.html).  But first try reading the log more carefully and see if there are other errors that might explain it.
