### ISSUE TITLE
Add move semantics to kaldi Matrices and Vectors.

### ISSUE THREAD

**Issue by galv** [kaldi-asr/kaldi#2037]
It would be good to add move semantics to Kaldi vector and matrices by making assignment operators and copy constructors that take in universal references, now that Kaldi has been C++11 compliant for a while. They can simply call the existing Swap() member functions.

Would be easy to do for someone interested in contributing, or I'll get around to it at some point.

**Comment by danpovey** [comment]
I'm not sure that I want to go in this direction.

My concern is that by using some of these newer C++11 features, we'll make the code harder to understand for people who only know basic C++.  I have always tried to keep things as simple as possible (although this was thwarted to some extent by our use of OpenFst).

Also I don't think that, with the coding style as it currently is, there's much call for move semantics, because we generally output things to pointers rather than through return values.

**Comment by galv** [comment]
Okay, I just found an instance today where I was copying a Matrix to a vector of Matrix needlessly, since the Matrix I was copying was about to be destroyed (but I fixed this using Swap()).
