### ISSUE TITLE
Program is likely to break with new gcc

### ISSUE THREAD

**Issue by posophe** [kaldi-asr/kaldi#205]
Hello everyone !

RPMLint has noticed a code breaking in const-arpa-lm.cc with -strict-alising.
 I: Program is likely to break with new gcc. Try -fno-strict-aliasing.
W: kaldi strict-aliasing-punning const-arpa-lm.cc:551, 555, 580, 913

Kaldi has been built with gcc 5. The concerned lines are 551, 555, 580 and 913

**Comment by danpovey** [comment]
Thanks for letting us know!
Guoguo, can you please look at this?
Dan

**Comment by chenguoguo** [comment]
I'm wondering what is the best way to fix this. What I have in mind is to
use union instead of reinterpret_cast, for example, define a union as
follows:

union Int32AndFloat {
  int32 i;
  float f;
};

Then we replace reinterpret_cast with this union. Any ideas? If you think
this is a good solution, I'll go ahead and apply the change.

Guoguo

**Comment by danpovey** [comment]
Hm.
I think it will be easier to add  -fno-strict-aliasing to the
EXTRA_CXXFLAGS in lm/Makefile.
Dan

**Comment by danpovey** [comment]
Actually, after reading this intro to the strict-aliasing rule
http://cellperformance.beyond3d.com/articles/2006/06/understanding-strict-aliasing.html
I think it would be better to make it a union, as you suggested.
Dan

**Comment by chenguoguo** [comment]
Just sent a pull request... I'll use the union solution then..

Guoguo

**Comment by jtrmal** [comment]
is this resolved?

**Comment by chenguoguo** [comment]
Yeah it has been checked in.

Guoguo

**Comment by jtrmal** [comment]
Closing, as it's been fixed in #211
