### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by voidxb** [kaldi-asr/kaldi#2095]
Hi,could you please tell me how to use kaldi as a library for developing an application in Android .Kaldi is very complex ,includes c++,shell,perl and it has a big size,10G + after compiling in linux ,4G + in Android.I have no idea how to do it.I want a .so file and .jar in the end.

**Comment by danpovey** [comment]
This is a big and difficult question.  I believe it's possible to compile Kaldi for android -- look at the "configure" script in src/-- but before you even think about building an application you'd have to think carefully about which parts of Kaldi you need.  Making speech recognition run on phones is nontrivial for speed and memory reasons and we haven't put much effort into making this process easy; rather, we've focused mostly on server-based applications.  My suggestion: just give up because the scope of the project is probably larger than you realize.
