### ISSUE TITLE
Problems about compile on windows with vs2017

### ISSUE THREAD

**Issue by weizhenzhao** [kaldi-asr/kaldi#2117]
![image](https://user-images.githubusercontent.com/13706689/34466175-a3ab751c-ef05-11e7-8eb0-747e5a75d292.png)

when I following the instructions of (https://github.com/kaldi-asr/kaldi/blob/master/windows/INSTALL.md)
to compile the Kaldi on window platform with vs2017 and openBLAS support.
I mat a problem said above.
It says that "ssize_t " in the openFST (c:\Users\95890\Documents\GitHub\openfst\src\include\fst\types.h)
redefinition.
I also see that in the readme in kaldi/windows said that
the compile will fail because of the missing of some file.
But I think the problem I met was not due to that.
So my question is that:
1、can you help me solve that problem?
2、Can that kaldi compile successfully in windows platform?

Thanks
WeiZhen

**Comment by danpovey** [comment]
If you get an error you should paste the exact error rather than attempting
to describe it.
Windows compilation is always going to be difficult and we don't always
have time to help with these issues; often we don't even have a Window
machine with the right software versions to reproduce the specific
problem.  Your best best is to figure it out yourself and report it to us
so we can fix it if possible.

Compiling Kaldi on Windows is only suitable for experts, e.g. for deploying
systems.  If your aim is to train on Windows then you are wasting your time.
