### ISSUE TITLE
Multhreaded FST operations

### ISSUE THREAD

**Issue by bkj** [kaldi-asr/kaldi#2156]
Hi all --

Are the implementations of the FST operations used in Kaldi (like `fstdeterminizestar`, `fsttablecompose`, etc) single-threaded or multi-threaded?  And if they're only single-threaded, is that because of some algorithmic restriction or would a multithreaded implementation be possible?

Thanks

**Comment by danpovey** [comment]
They're single threaded.  And yes, it's because of algorithming
restrictions-- making multi-threaded versions would be quite complicated.
We're starting to spec out a dynamic decoder, which might help to reduce
the latency when you start with a new language model or lexicon.  But it
won't be done for at least a few months.

**Comment by bkj** [comment]
Great -- thanks for the quick response!

**Comment by Ruarosh** [comment]
Hi
It would be a great help if parallelization is implemented in fst(like fstdeterminizestar, fsttablecompose, etc), especially when the lm is very big and the training may take a few hours, is there a plan to implement the multithread edition?

**Comment by Ruarosh** [comment]
Thanks a lot for quick response, we have being doing as your advice and if parallelization is realized， it would be more helpful.
