### ISSUE TITLE
kaldi-android build failed with "use of undeclared identifier 'aligned_alloc'"

### ISSUE THREAD

**Issue by nuekodory** [kaldi-asr/kaldi#2347]
Hello.
I've read [Compile Kaldi for Android - Clean Blog](http://jcsilva.github.io/2017/03/18/compile-kaldi-android/) and carefully followed the instruction.
When I tried `make -j 6` for `kaldi-android/src`, I got some errors relating to aligned_alloc.
I also tried [build with docker](https://github.com/jcsilva/docker-kaldi-android) and got the same errors.

ERRORS:

```
kaldi-matrix.cc:56:11: error: use of undeclared identifier 'aligned_alloc'
          aligned_alloc(16, sizeof(Real)*l_work))) == NULL) {
          ^
kaldi-matrix.cc:715:11: error: use of undeclared identifier 'aligned_alloc'
          aligned_alloc(16, sizeof(Real)*l_work))) == NULL)
          ^
kaldi-matrix.cc:806:23: error: use of undeclared identifier 'aligned_alloc'
  if (NULL != (data = aligned_alloc(16, size))) {
                      ^
packed-matrix.cc:71:15: error: use of undeclared identifier 'aligned_alloc'
  if ((data = aligned_alloc(16, size * sizeof(Real))) != NULL) {
              ^
sp-matrix.cc:227:11: error: use of undeclared identifier 'aligned_alloc'
          aligned_alloc(16, sizeof(Real) * rows))) == NULL) {
          ^
```
My environment:
- Ubuntu 16.04 LTS
- glibc 2.23 (from package libc-bin, 2.23-0ubuntu10)

I searched and found that this could came from older glibc version, and I tried on Ubuntu 17.10 with glibc 2.26 and result are the same.

**Comment by danpovey** [comment]
We recently changed that code to use aligned_alloc instead of a system-dependent ifdef.
aligned_alloc is supposed to be a C++11 feature, and is supposed to be available if you include <cstdlib>, which we do, so this is likely a bug or issue somewhere else than Kaldi (e.g. in the Android NDK).

Possibly it's related to this:
 https://github.com/android-ndk/ndk/issues/421
which seems to be an issue with NDK r15 and possibly later, with armeabi-v7a.  The instructions
here http://jcsilva.github.io/2017/03/18/compile-kaldi-android/
do reference NDK r16, and armeabi-v7a.  But I'm not an android expert.  You could maybe get help by trying things mentioned in the issue  https://github.com/android-ndk/ndk/issues/421 or from @jcsilva.  Please let us know any changes we can make to resolve this issue.

I'd rather not revert the code to how it was before we used aligned_alloc, because it is supposed to be a c++11 feature, and c++11 is allegedly supported there.

**Comment by jtrmal** [comment]
@danpovey, it seems that aligned_malloc is C++17, at least according to
this: http://en.cppreference.com/w/cpp/memory/c/aligned_alloc
I have also found it's ISO C 11 function here:
https://linux.die.net/man/3/aligned_alloc, but I'm not very sure how C and
C++ library functions align.
y

**Comment by danpovey** [comment]
Wait a minute.
I see now that I was wrong about aligned_alloc.  It is not a c++11 feature, it is a C11 feature (not the same thing), although it is part of c++17 (http://en.cppreference.com/w/cpp/memory/c/aligned_alloc).
I'll try to fix this today-- I may just revert the patch where we switched to using aligned_alloc, if I don't find another fix.

**Comment by danpovey** [comment]
@jtrmal, do you have time to revert the changes in the cygwin patch that relate to aligned_alloc, and revert to an approach similar to what we previously used with posix_memalign?  The 'revert' button doesn't work, likely due to conflicts.
But I notice that the macros had an unnecessary last parameter 'to_free' or 'tmp' or something, which apparently was never used any more, so I think it would make sense to remove that.

**Comment by jtrmal** [comment]
I'm on my way to bed, actually, but I can do it first thing tomorrow
morning.
Y.

**Comment by danpovey** [comment]
@galv, do you have time for this?  If not I can do it tonight.

**Comment by nuekodory** [comment]
@danpovey Thank you a lot, now it seems to be okay...
(Please be patient for while, since my machine's extremely slow)
I write a comment if whole build process is completed.

**Comment by nuekodory** [comment]
Kaldi-android build succeeded. Thanks @danpovey @jtrmal
