### ISSUE TITLE
how to fine-tune a tdnn model ?

### ISSUE THREAD

**Issue by ericyue** [kaldi-asr/kaldi#2374]
I have a pre-trained tdnn model (or a nnet3 model), is there a way to fine tune this pre-trained model with new speech-data ?  I cannot find any docs about this.

**Comment by danpovey** [comment]
Yes it's possible.
Assuming this is a 'chain' model, you can use something along the lines of
egs/rm/s5/local/chain/tuning/run_tdnn_wsj_rm_1c.sh
Similar things are possible with regular (non-chain) nnet3 models too, I think.
If it uses iVectors, be sure to use the same iVector extractor.

**Comment by v-yunbin** [comment]
@danpovey  Excuse me
- When i train a 'chain' model with starting from scratch, everything went smoothly.
- But i do fine tune with pre-trained gmm model with new speech-data, using script "egs/rm/s5/local/chain/tuning/run_tdnn_wsj_rm_1c.sh", met follows errors, and the reason is generation failed.
**Look forward to your reply.**
##########################errors##############################
2019-04-30 19:58:58,871 [steps/nnet3/chain/train.py:359 - train - INFO ] Generating egs
steps/nnet3/chain/get_egs.sh --frames-overlap-per-eg 0 --cmd run.pl --cmvn-opts --norm-means=false --norm-vars=false --online-ivector-dir  --left-context 23 --right-context 23 --left-context-initial -1 --right-context-final -1 --left-tolerance 5 --right-tolerance 5 --frame-subsampling-factor 3 --alignment-subsampling-factor 3 --stage -10 --frames-per-iter 1000000 --frames-per-eg 150 --srand 0 data/train_hires exp/chain/tdnn_datatang_aishell2_1a exp/tri3_lats exp/chain/tdnn_datatang_aishell2_1a/egs
utils/data/get_frame_shift.sh: data/train_hires/utt2dur does not exist: creating it
utils/data/get_utt2dur.sh: segments file does not exist so getting durations from wave files
cat: write error: Broken pipe
utils/data/get_utt2dur.sh: could not get utterance lengths from sphere-file headers, using wav-to-duration
steps/nnet3/chain/train.py --stage -10 --cmd run.pl --use-gpu=wait --trainer.input-model exp/chain/tdnn_datatang_aishell2_1a/input.raw --feat.online-ivector-dir  --chain.xent-regularize 0.1 --feat.cmvn-opts --norm-means=false --norm-vars=false --chain.xent-regularize 0.1 --chain.leaky-hmm-coefficient 0.1 --chain.l2-regularize 0.00005 --chain.apply-deriv-weights false --chain.lm-opts=--num-extra-lm-states=200 --egs.dir  --egs.stage -10 --egs.opts --frames-overlap-per-eg 0 --egs.chunk-width 150 --trainer.num-chunk-per-minibatch=128 --trainer.frames-per-iter 1000000 --trainer.num-epochs 2 --trainer.optimization.num-jobs-initial=2 --trainer.optimization.num-jobs-final=4 --trainer.optimization.initial-effective-lrate=0.005 --trainer.optimization.final-effective-lrate=0.0005 --trainer.max-param-change 2.0 --cleanup.remove-egs true --feat-dir data/train_hires --tree-dir exp/chain/tri4_5a_tree --lat-dir exp/tri3_lats --dir exp/chain/tdnn_datatang_aishell2_1a
['steps/nnet3/chain/train.py', '--stage', '-10', '--cmd', 'run.pl', '--use-gpu=wait', '--trainer.input-model', 'exp/chain/tdnn_datatang_aishell2_1a/input.raw', '--feat.online-ivector-dir', '', '--chain.xent-regularize', '0.1', '--feat.cmvn-opts', '--norm-means=false --norm-vars=false', '--chain.xent-regularize', '0.1', '--chain.leaky-hmm-coefficient', '0.1', '--chain.l2-regularize', '0.00005', '--chain.apply-deriv-weights', 'false', '--chain.lm-opts=--num-extra-lm-states=200', '--egs.dir', '', '--egs.stage', '-10', '--egs.opts', '--frames-overlap-per-eg 0', '--egs.chunk-width', '150', '--trainer.num-chunk-per-minibatch=128', '--trainer.frames-per-iter', '1000000', '--trainer.num-epochs', '2', '--trainer.optimization.num-jobs-initial=2', '--trainer.optimization.num-jobs-final=4', '--trainer.optimization.initial-effective-lrate=0.005', '--trainer.optimization.final-effective-lrate=0.0005', '--trainer.max-param-change', '2.0', '--cleanup.remove-egs', 'true', '--feat-dir', 'data/train_hires', '--tree-dir', 'exp/chain/tri4_5a_tree', '--lat-dir', 'exp/tri3_lats', '--dir', 'exp/chain/tdnn_datatang_aishell2_1a']

**Comment by danpovey** [comment]
It looks to me like it was working, actually.  We need to suppress that
warning.  @hanglv can you please make a PR to fix it?
I think in get_utt2dur.sh we just have to change `cat $data/wav.scp` to
`cat $data/wav.scp 2>/dev/null`

**Comment by v-yunbin** [comment]
@danpovey but two recipe use same speed-perturb data and same format for wav.scp. 
maybe problem is the tuning script?

**Comment by danpovey** [comment]
It wasn't crashing, it was working.  The `cat: write error: Broken pipe`
was not fatal for the script.

**Comment by v-yunbin** [comment]
@danpovey generate utt2dur with python package "librosa" for any format "wav.scp"
#############################################
import librosa
with open(wavscp,"r") as file:
	for line in file:
		cells = line.split()
		id = cells[0]
		for c in cells[1:]:
			if ".wav" in c:
				path = c
			else:
				pass
		time = librosa.get_duration(path)
		print(id+" "+str(time)+" \n")

**Comment by danpovey** [comment]
Thanks, that's cool.  See whether librosa is usually installed by default
or has to be installed.  We don't like to add too many dependencies.

**Comment by v-yunbin** [comment]
@danpovey ”line 69-70“ is not clear  for the  shell script `local/prepare_wsj_rm_lang.sh` in `egs/rm/s5/local/chain/tuning/run_tdnn_wsj_rm_1c.sh`.
paste codes as follows:
`stcompile --isymbols=$output_dir/words.txt --osymbols=$output_dir/words.txt --keep_isymbols=false \
    -keep_osymbols=false data/local/tmp/G.txt | fstarcsort --sort_type=ilabel > $output_dir/G.fst || exit 1;`
The file "data/local/tmp/G.txt" had nerver been mentioned.

**Comment by danpovey** [comment]
sorry that script is very old and I don't want to spend time fixing it, but if you figure out the fix I can merge it.
