### ISSUE TITLE
transition to python 3

### ISSUE THREAD

**Issue by leomao** [kaldi-asr/kaldi#2410]
According to [PEP 373](https://www.python.org/dev/peps/pep-0373/), python 2 will reach its EOL in 2020.  I think It's time to migrate scripts to python3.  Is there any plan for this?

**Comment by danpovey** [comment]
Yes there is a plan.
The current status is that new scripts are written in python3 and invoked as '#!/usr/bin/env python3'.  Existing scripts, are invoked as '#!/usr/bin/env python' but we modify them such that they should be compatible with python3.  Whenever we get reports of things not working (on systems where python3 is the default) we fix them.  Since Kaldi is kind of sprawling, there will likely continue to be bugs reported for a long time, but we fix them when notified.
