### ISSUE TITLE
ConstFst::Read: Read failed: <unspecified>

### ISSUE THREAD

**Issue by Excalib88** [kaldi-asr/kaldi#2458]
Hi all. I try to use kaldi for recognition with my model. But i get such error(i attach link in the pastebin under text) If you can help me decide this problem i will be grateful. If you have a ready assembly for Windows then it will be very excellent, Thank you for such Great!!!
https://pastebin.com/NtaswnAA

**Comment by danpovey** [comment]
It looks like you are on Windows.  Problems are to be expected.
To narrow it down you could see whether that file is nonempty, and try to
see if running 'fstcopy' on it (to a different file location) works or
crashes.  If it fails then it's likely the issue is in the FST code (-->
harder to fix, but maybe still possible); if it works it might be a
kaldi-specific issue that we could more easily fix.

Dan

**Comment by kkm000** [comment]
@danpovey, I'm on it, ok to close. This was supposed to be fixed, they might just have a  pre-fix code snapshot.

**Comment by kkm000** [comment]
Xref kkm000/openfst/issues/11

**Comment by danpovey** [comment]
Thanks, @kkm000!
