### ISSUE TITLE
How to train DNN model with nnet2 or nnet3?

### ISSUE THREAD

**Issue by v-yunbin** [kaldi-asr/kaldi#2493]
1. I have train model with nnet1 but i do not konw how to kick off train with nnet2 or nnet3
if i want to use nnet2 or nnet3, need to configure some parameter or compiling in tools ?
2. whether i can to retrain a DNN model based on a prepared DNN model with own data?

**Comment by danpovey** [comment]
You should follow an example script that uses nnet2 or nnet3.  e.g. mini_librispeech.  And adapt that to your data.
I don't know what you mean by the 2nd question but in any case the answer is probably going to be no, simply because it might be complicated and you seem too clueless to do it.  See kaldi-asr.org/forums.html for how to ask questions.

**Comment by v-yunbin** [comment]
@danpovey I think it's amazing. You're ridiculous.
