### ISSUE TITLE
Pipe stream for FST fails via OpenFST calling istream tellg

### ISSUE THREAD

**Issue by Downchuck** [kaldi-asr/kaldi#2509]
Gave a quick try at '/bin/gunzip -c ./HCLG.fst.gz |' -- which leads to 
```
ERROR: AlignInput: Can't determine stream position
ERROR: ConstFst::Read: Alignment failed: <unspecified>
```
From OpenFST
```
bool AlignInput(istream &strm) {
  char c;
  for (int i = 0; i < MappedFile::kArchAlignment; ++i) {
    int64 pos = strm.tellg();
    if (pos < 0) {
      LOG(ERROR) << "AlignInput: can't determine stream position";
      return false;
    }
    if (pos % MappedFile::kArchAlignment == 0) break;
    strm.read(&c, 1);
  }
  return true;
}
```
My understanding is that the file gets loaded into memory anyway, but OpenFST is expecting istream whereas Kaldi IO is (reasonably) returning an istream popen tellg that is not overloaded to increment on read. That said, OpenFST does have an LZA compression extension. This just may have been easier for a quick hack.

**Comment by Downchuck** [comment]
Going to close this bug report -- doesn't appear worth the effort to try to build this in.

**Comment by danpovey** [comment]
Likely that is a ConstFst, which is optimized for loading via memory
mapping.  I guess the OpenFst people have decided not to support gzipped
files for that case because it would defeat the efficiency of memory
mapping.
I think it's an inherent limitation which likely can't be worked around by
changing Kaldi code.

On Sun, Jun 17, 2018 at 8:58 AM, Charles Pritchard <notifications@github.com

**Comment by Downchuck** [comment]
Confirmed that it was just my FST; gunzip works fine when I take out alignment via:
```
fstprint HCLG.fst | fstcompile --fst_type=const --fst_align=false - UNAL.fst
```

I don't know that alignment is necessary -- it seems to be the new default to be unaligned in the OpenFst code base.
