### ISSUE TITLE
Is there a data race in kernel function _trace_mat_mat_trans located in src/cudamatrix/cu-kernels.cu?

### ISSUE THREAD

**Issue by DayDayStudyNightNightUp** [kaldi-asr/kaldi#2604]
Hello there!

Currently i am learning kaldi's source code, and may find a data race in in kernel function _trace_mat_mat_trans.

From line 1059 to line 1064:
  ```
if (tid < warpSize) {
#   pragma unroll
    for (int shift = warpSize; shift > 0; shift >>= 1) {
      ssum[tid] += ssum[tid + shift];
    }
  }
```

where tid is defined in line 1034:
```
 const int32_cuda tid = threadIdx.y * blockDim.x + threadIdx.x;
```

Let's assume we have two threads (0 0 0) and (1 0 0) and warpSize = 32. // (threadIdx.x threadIdx.y threadIdx.z)
Then the tid of (0 0 0) is 0, the tid of (1 0 0) is 1. When the loop terminates, shift will come to be 1. Meanwhile, for thread (0 0 0), ssum[0] += ssum[0 + 1] will be executed; for thread (1 0 0), ssum[1] += sth will be executed . 
Is there a read & write synchronization issue here? For instance, thread (0 0 0) reads data from ssum[1] while thread (1 0 0) tries to write data in ssum[1] ?  

Thanks for the help! :)

**Comment by danpovey** [comment]
@kangshiyin, can you please check this?

**Comment by kangshiyin** [comment]
hi @DayDayStudyNightNightUp 

You are correct that `ssum[0] += ssum[0 + 1]` and `ssum[1] += ssum[1 + 1]` are executed at the same time.  But since we are now in a warp, all the 32 threads (tid=0..31) are synchronized. So reading data from **_`ssum[1]`_** and `ssum[2]` always happens before writing data to `ssum[0]` and **_`ssum[1]`_** for thread tid=0 and tid=1.

You could refer to page 14 of the following doc for more details about parallel reduction.
https://developer.download.nvidia.com/compute/cuda/1.1-Beta/x86_website/projects/reduction/doc/reduction.pdf
