### ISSUE TITLE
TDDN-F

### ISSUE THREAD

**Issue by Lallapallooza** [kaldi-asr/kaldi#2646]
Hello, I want to make tdnnf with stats pooling.
Nnet conf below.

```
input dim=${feat_dim} name=input
relu-batchnorm-layer name=tdnn1 input=Append(-2,-1,0,1,2) dim=768

tdnnf-layer name=tdnnf1 dim=768 bottleneck-dim=128 time-stride=2

stats-layer name=stats config=mean+stddev(0:1:1:${max_chunk_size})

relu-batchnorm-layer name=tdnn2 dim=512 input=stats
relu-batchnorm-layer name=tdnn3 dim=512

output-layer name=output include-log-softmax=true dim=${num_targets}
```

And I have an error.
Inconsistent value for sum descriptor: for node 6, it can have scales 0.66 vs. inf (you have used unsupported combinations of descriptors).

**Comment by danpovey** [comment]
Did you compile with -Ofast?  Because I looked at the code and that seems to me to be the only way you could get that error.
@vimalmanohar, would you mind, next time you commit something, adding a test for this, e.g. in kaldi-error.cc?

E.g. (but test it):
bool a = std::pow(1.0e+10, 1.0e+10);  // infinity but don't let compiler know.
KALDI_ASSERT(a - a == 0 && "Did you compile with -Ofast?  That is not allowed.");
