### ISSUE TITLE
nnet3 : inconsistency in the way --ivector arguments are defined

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#275]
nnet3-compute and nnet3-get-egs define the --ivector argument differently.

nnet3-compute expects per-utterance vectors and nnet3-get-egs expects --ivectors to be feature matrices. Is there a reason for this inconsistency ?

**Comment by danpovey** [comment]
Hm.  I don't think there is a very good reason for it.  Note: nnet3-compute
does accept the the --online-ivectors option which is similar to
nnet3-get-egs's --vectors-option (except nnet3-get-egs doesn't accept
anything like the --online-ivector-period option).  Possibly modifying
nnet3-get-egs to accept instead options named --online-ivectors and
--online-ivector-period would be more consistent - if you have time.
Dan

**Comment by vijayaditya** [comment]
OK will do this.

--Vijay

**Comment by vijayaditya** [comment]
Sorry I am unable to get these done. There are two other closed issues
 which haven't been resolved (see below). I will try to get them done later
this month.

https://github.com/kaldi-asr/kaldi/issues/378
https://github.com/kaldi-asr/kaldi/issues/309

--Vijay

**Comment by vijayaditya** [comment]
I would appreciate it if someone else can take up this issue. I might not be able to work on this till mid-April.

**Comment by danpovey** [comment]
nnet3-compute has an online-ivectors option which you can use to provide
online ivectors.
Probably the easiest and also most correct fix for this problem would be to
rename the ivectors option of nnet3-get-egs to online-ivectors, and change
the script accordingly.
However, to be completely compatible we'd have to also supplyi the
--online-ivector-period flag and change the scripts so that they used that
flag just supplied the raw online ivectors without adding repeats (i.e.
take the subsample-feats out of the pipeline).
Since this is just a cosmetic issue it is very low priority for me.
Dan
