### ISSUE TITLE
ERROR: VectorFst::Read: Read failed: tmpdir.g/empty_words.fst on CygWin of Win7

### ISSUE THREAD

**Issue by jefferydai** [kaldi-asr/kaldi#2804]
Hello,

I encountered the issue when running the run.sh under kaldi\egs\yesno\s5 in CygWin of Win7. Below is the part of output:
$ ./run.sh
Preparing train and test data
......
Preparing language models for test
......
'E:\Audio\Kaldi\kaldi\kaldiwin_vs2017_OPENBLAS\x64\Debug\fstisstochastic.exe' data/lang_test_tg/G.fst
1.20397 1.20397
**ERROR: VectorFst::Read: Read failed: tmpdir.g/empty_words.fst**

I read the official document of installing/compiling kaldi on Windows (VS 2017) , then I install and compile kaldi in VS2017 after modifying some kaldi's error on VS 2017. Now the all projects (630) are compiled successfully. 

Can you please help resolve this issue?

Is there anyone successfully runs the run.sh under egs\yesno\s5? 
I am not sure if the current kaldi can run on CygWin as I saw some links saying we can only run the shell scripts on Linux.

Thank you very much!

**Comment by danpovey** [comment]
Sorry - not all of the scripts will work right if you compile Kaldi using Visual Studio.  In fact, hardly any of them will work.  It has to do with what happens when processes are invoked from C++; basically, it won't go to the UNIX shell equivalent (cygwin), it will go to cmd (i.e. the DOS shell).  Instructions for compiling with Visual Studio are provided for other purposes, but training definitely won't work.   You may be able to compile from inside cygwin, but honestly, I doubt this will work.  cygwin has not been very stable in recent years, and there isn't enough demand for Kaldi in Windows for us to spend time debugging the problems that can happen on all the different versions of windows and cygwin.
