### ISSUE TITLE
Convert .ark file to .csv file

### ISSUE THREAD

**Issue by bar13290** [kaldi-asr/kaldi#2927]
Hi,
Is there a way to convert the MFCC features that extracted with Kaldi (.ark file) to a .csv file that include all the parameters of the  MFCC matrix?

Thanks

**Comment by jtrmal** [comment]
it's not trivial, because MFCC ark contains name+matrix, so you'd have to
figure out how to format the data into a csv
you can play with copy feats, for example:

copy_feats scp:feats.scp ark,t:-

it should be fairly easy to convert the output to matlab matrix (for
example) or post-process the output using sed.
y.
