### ISSUE TITLE
Nnet3 training chrashing and rebooting server

### ISSUE THREAD

**Issue by anderleich** [kaldi-asr/kaldi#3111]
Hi,

I'm facing some problems when training a nnet3 acoustic model. I've previously trained some other models, all without any similar issue. However, this time, I'm trying to train a model for a different language. All goes perfectly until it gets to the nnet3 training phase. It runs for a few iterations until it crashes and reboots the server. I can't get past these iterations, everytime I try it crashes at some point.

I've monitored the server resources, but I'm not able to see anything weird. The server has two Nvidia GPUs configured to exclusive mode. GPU memory is half used. No RAM issues either. I can't find a solution.

Has someone experienced something similar? Is it possible to be crashing due to agreat amount of training data (around 500h)? Or a huge Language model (1 bilion words)?

Thanks

**Comment by danpovey** [comment]
Usually this would be due to improperly configured hardware, with a power supply unit that is not sufficient for a fully loaded GPU.  You should really complain to whoever you bought the hardware from.
However, not all dealers are equally reputable.  Here at CLSP we once bought some GPU machines from a supplier who I won't name, and they would randomly reboot every few weeks; they were not necessarily even much loaded; it wasn't a power supply issue, it was probably some kind of motherboard issue. 
We mostly use Dell now, they offer better support.  It's not that our hardware doesn't fail; it does, frequently; it's more that we have a recourse, and a mechanism to get, say, a motherboard replacement or a new GPU card or GPU riser.
