### ISSUE TITLE
Less heavyweight std::shared_ptr replacement ?

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#3270]
This is a not-so-urgent issue for the new tensor stuff, but I'd like to think about it and maybe eventually do something about it.  Also it's cleanly separable from the other stuff I'm working on.   I'm thinking of having a replacement of std::shared_ptr that does the atomics only where necessary, and to have it be under user control, so a user can say whether the tensors generated during a particular part of the program are expected to be shared across multiple threads.    That would avoid having to worry too much about the overhead of std::shared_ptr (which can be substantial if a program has >1 thread, I believe).

The basic idea is to have a thread_local variable, say, `thread_local bool g_safe_shared_ptr;` with a getter/setter function and mechanisms to set it within a scope.   Then there would be a rewritten version of std::shared_ptr which would only use atomics if (a) the program has >1 thread, and (b) g_safe_shared_ptr is true.  Part (a) is, I believe already the case for std::shared_ptr, see https://stackoverflow.com/questions/25780826/whats-the-overhead-from-shared-ptr-being-thread-safe where it says `If only one thread of execution exists in the program then less expensive non-atomic operations are used`.

The idea is that typically when constructing a computation graph in something like PyTorch, it will be accessed from only one thread and objects created there won't be accessed from another thread-- but the model parameters, for instance, might be accessed from multiple threads.  The boolean variable sets a corresponding variable in the shared_ptr objects, so a shared_ptr created with the `safe` setting would always be accessed in the `safe` way.  

I was thinking maybe @hainan-xv could work on this, possibly with @kkm000 and/or @galv giving advice.  

If we decide to do this, even if it will take a little while, I could go ahead and design other stuff without spending too much effort worrying about the overhead of shared_ptr, assuming we'll replace it with our version, e.g. kaldi::shared_ptr (or some other less confusing name) at some point in the future).  I assume this will also work with pybind11.  I notice you can use std::shared_ptr as a memory management mechanism when  doing pybind11 binding, but I think it's treated as a generic wrapper class rather than something built into pybind11.

**Comment by kkm000** [comment]
I do not think that atomics are heavyweight in any sense. If we need refcounted pointers, then we need them, and the shared_ptr is the only proper way to go. I do not know about more exotic platforms, but I think it's safe to say that at the least 95% of the world is running HPC on x64-compatible CPUs, where atomics cost next to nothing. (And they probably should on any platform suitable for HPC, anyway).

**Comment by danpovey** [comment]
Oh.  I see people claiming that they about 100 times slower than a normal
operation, which seemed to me potentially significant.  I thought it might
be an issue, and I seem to remember there was some Kaldi program where we
had to reduce the use of shared_ptr because it was too much overhead.

**Comment by kkm000** [comment]
It's hard to guess what the "100 times" claim is about (there is not a way to time a single instruction in a CPU, so what is divided by what?), but it sounds rather like one of those that require extraordinary evidence. :)

No, I would be really surprised if non-atomic shared pointer would be a low-hanging fruit. And I would certainly stay away from having to deal with two types of shared pointers and risking threading heisenbugs until I'd be very certain that it will give me a performance gain in single percent range overall.

**Comment by danpovey** [comment]
@desh2608 can you please do some tests?
This guy has some tests
http://www.modernescpp.com/index.php/memory-and-performance-overhead-of-smart-pointer
which might be a good place to start, but it's single-threaded, which might mean it is not even using atomics.  Look into C++11 threads, they are quite easy to use.  Ask @hainan-xv if you get stuck.  Also, doing new and then immediate delete on the same thing might allow it to optimize some things entirely away so not sure how realistic that is.  But it's a reasonable place to start.

**Comment by desh2608** [comment]
Yeah, sure.

**Comment by kkm000** [comment]
I'd look closely at the assembly listing of generated code, at the very least. This does not look like a carefully written test. Compilers are smart enough to optimize out the whole new/delete thing (or, speaking of optimizations, the x_ptr construction, or the whole loop as well).

The reference point in the test looks rather arbitrary. "how many times faster/slower is x_ptr compared to `new int(1)`" -- what is so special about the timing of `new int(1)` (plus an unknown loop overhead)?

**Comment by kkm000** [comment]
@danpovey, what is the overall design idea of this thing? I am thinking of something vague here. When something is accessed from PyTorch, then we do not care about the speed at all; anything in Python is going to be slower than anything we can do with the pointers, and I am really talking many order of magnitude slower. Also, any reference counting is involved only when the object ownership somehow changes (i. e. shared/unshared). So if model parameter objects are owned by the model, in the sense that live model implies that parameters cannot be deleted, then they can be updated by their dereferenced pointer, not involving reference counting. Again, if the parameter is a matrix, and it can be updated from multiple threads, then the fact that the pointer is thread-safe (in the sense that we have a guarantee that the object does not go away while we are holding a copy of shared_ptr) does not solve the entire problem; access to the parameter needs to be protected anyway. So if we deal with an atomic matrix (with no support from the CPU at all, so that requires a mutex), then what is the problem with an atomic integer reference count?

It seems to me that I do not understand something really important here. To me, if performance of atomic increments/decrement is becoming important, then the pointers are somewhere in the critical computation path, and in a really big way, like, for example, an access to an element of a matrix always implies copying/referencing a pointer. But this cannot be the case, it would be a performance killer anyway. I cannot understand how pointer *sharing* got into the critical path (and, if it's inevitable, how it could still be practically usable etc.) I'm just thinking of the criteria which push the performance of the reference counting arithmetic to the front row:
 * Access from C code to C code (Python is so slow that speed is irrelevant).
 * in a way that requires reference counting (so that an object is passed to another thread, for example, or stored in another object, so we are not talking about a stack-constructed object).
 * happens so often that we start worrying about the performance of the atomic vs non-atomic `n++`.

I just cannot think of a more or less realistic situation that would satisfy these. The second point seems to imply there is a thread or memory allocation, which is certainly on a different time scale than an atomic increment, unless I did not think of some other practical scenario. So what is actually happening here?

> The boolean variable sets a corresponding variable in the shared_ptr objects, so a shared_ptr created with the safe setting would always be accessed in the safe way.

I do not think this could realistically be an improvement, i. e. that branching + non-atomic increment could potentially beat non-branching atomic increment. The `if (safe)` here will be the most time-consuming operation.

**Comment by danpovey** [comment]
It's really just the meta-information, and it's nothing to do with
accessing things element by element.
I have seen people saying that shared_ptr can be 100 to 200 times slower
than, new/delete, although I'm not sure how much to believe this and what
architecture it applies to.  If it's really just equivalent to a handful of
normal instructions it would be OK.  But I do remember that we encountered
a situation in Kaldi where the shared_ptr overhead was significant even
though they were holding fairly big objects that needed to be processed.
So I'm just not sure that I believe that it's as fast as you say it is.

**Comment by kkm000** [comment]
I'll try to construct a more sensible test. Like N objects of size M, with an int32_t and atomic<int32_t> members that are randomly accessed by pointer and passed to functions that do the increment. Then vary N and M by an order at a time. Then maybe pass even shared_ptr by value (i. e. triggering refcounting twice) vs. passing by a C pointer. The most sensible measure, I believe, is the wall clock--the CPUs are so intricate that it is hard to compare the timing of operation X to operation Y, these are not well-defined for little operations like increment or CAS (and T(X)/T(Y) may not be an interesting ratio if both are very small). I think it's a good thing to get out of the way, in any case.

I am skeptical about the method that yielded the figure times 100. It's possible to get any number huge compared to e. g. the statistical average of a register n++. I'm not saying they intentionally constructed a test to prove the point, just that the compiler could have done a much smarter thing than they expected. :)

**Comment by danpovey** [comment]
You don't have to do this yourself, @desh2608 can follow your advice.

**Comment by kkm000** [comment]
Thanks. I'll see how we can split that.

I found some interesting measurements: https://spcl.inf.ethz.ch/Publications/.pdf/atomic-bench.pdf, although a good part of it flew way above my head.

My understanding is that the bandwidth and latency metrics that they model are the most pertinent to lock-free parallel HPC algorithms. How much are the numbers relevant otherwise, I cannot say, depends on too many things, like branch misprediction etc. E. g. they find that atomic latency exceeding read latency by 5-10 ns (on Haswell), and read latency can be say 2-3 ns. Even 5ns translates to a significant number of CPU cycles, but there is a lot of stuff in the pipeline besides the atomic instruction, so dividing latency by cycle time makes no sense, although it gets us close to the claimed order of hundreds. But a non-atomic increment also has to be scheduled ahead to read from the cache some time before the increment instruction is actually executed. So I could rather divide the average 10ns by 2.5ns, but again, will it reflect the average of atomic/non-atomic increment performance? May be irrelevant (just stuff sitting in the pipeline longer, put there way ahead of a simple read), may be just that, 4 times. And even of so, again, what should I glean from this figure "4 times longer?" How does it alone translate to overall performance? Amazingly complex stuff, and I am sure that what I understand of it is still rather a naive simplified theory. I have a much better trust in the results obtained with a profiler on real code execution than even a well-designed artificial test. Any premature optimization is a shot in the dark, much more likely to miss the mark. (And all Kaldi code is compiled with the quite modest -O1 by default anyway.)

**Comment by danpovey** [comment]
Someone (I think @desh2608) did some tests and found that it was not excessively slower than unique_ptr, something like 6 times.  So I guess this isn't excessive.
