### ISSUE TITLE
utils/split_scp.pl broken

### ISSUE THREAD

**Issue by kkm000** [kaldi-asr/kaldi#3306]
After b17fc8447, `utils/split_scp.pl -j 16 3 src-lats.scp` outputs the chunk 4 of 16 to a regular file named `-` instead of STDOUT.

The reason is the "old" 2-argument form `open FH, ">-"` used to open a handle to STDOUT, while the "modern Perl" `open $fh, '>', '-'` creates a real file named `-` instead.

**Comment by kkm000** [comment]
I'm fixing that right now, have no choice, basically. ETA some time today.

**Comment by danpovey** [comment]
@kkm000 I just reverted #3307 as that's a potentially serious bug.
@xsawyerx perhaps now you see the wisdom of what I was saying when I said on your PR that I "don't like those types of changes" (w.r.t. the filehandle change).  I merged anyway because it's true that you were trying to be helpful.

**Comment by kkm000** [comment]
I have a fix, actually. Combining best of both.

**Comment by xsawyerx** [comment]
I understand the frustration and I'm sorry for the breakage introduced by what I was certain is an innocent change. I'm hoping the conclusion from this isn't "never change things," but to be more cautious and I apologize for that.

The change here, despite the breakage it created (which can be fixed!), still attempts to fix an insecure pattern. The way the arguments are opened, a parameter passed that includes opening arguments can overwrite files (and filehandles), rendering a system completely useless. It *should* be fixed instead of leaving an ostensibly-stable-yet-insecure code from lingering on.

**Comment by kkm000** [comment]
@xsawyerx, it's ok, do not worry. Many low-level scripts are old, tricky, and are used in may locations and in many ways.

**Comment by danpovey** [comment]
Yeah, Kirill is including your changes in his patch.
