### ISSUE TITLE
rbm pretrain error with cnn layer

### ISSUE THREAD

**Issue by colingogo** [kaldi-asr/kaldi#343]
I concatenated the feature_transform and the trained cnn layers, thus a new feature transform was derived. Then when I put it on the training data to do new rbm pretraining, error occurs like: KALDI_ASSERT: at rbm-train-cd1-frmshuff:CopyCols:cu-matrix.cc:1953, failed: NumRows() == src.NumRows().
I have no idea about this error, does anybody know it ? Thanks very much.

**Comment by danpovey** [comment]
Sounds like a feature dimension mismatch.

**Comment by colingogo** [comment]
when I removed the CNN layers, job became ok.
CNN layers act like a feature projection, only dimension changes, I wonder whether the pretrain script has strict feature format or something. Do you have some advice? Thanks.

**Comment by danpovey** [comment]
Karel might be able to comment- this relates to nnet1 so I don't know.

**Comment by danpovey** [comment]
This kind of thing should go to the help forum, kaldi-asr.org/forums.html
'issues' is not for questions like this.

**Comment by vesis84** [comment]
Hi, this is strange, the dimensionality errors should cause Column mismatch, not row mismatch. I looks like some uninitialized buffer for some unknown reason. Could you please provide the stacktrace? Or ideally you could use gdb to see what is the dimensionality of the source of the target matrix?

Also be careful about the RBM, it should not have Gaussian input layer in this case but bernoulli one becaus of preceding sigmoids, use option "--input-vis-type bern".

Best,
Karel.

**Comment by branden65** [comment]
I also had the same issue.
I've carefully checked the code using gdb.

And I realized nnet-forward does not properly perform about convolutional layer.

Specifically,
in src/nnet/nnet-convolutional-component.h
line 243: if (vectorized_feature_patches_.NumRows() == 0) should be commented
otherwise "this" (pointer) information is not updated and keep having a previous row information (previous utterance's).

After fix this and compile,
I did not have any error.

Best,
Seongjun
