### ISSUE TITLE
A question on nnet3/chain training, regarding i-vectors

### ISSUE THREAD

**Issue by underdogliu** [kaldi-asr/kaldi#3535]
Hi all! So just a quick question on nnet3: every time when we are initialising the training process, whether it's regular nnet3 or chain models, we always have an extra 100 dimension for i-vectors as input features. It works well on slightly improving WERs but just wondering if there is any published evidence on this feature? Thanks!

**Comment by danpovey** [comment]
I don't  believe we published any paper where this was the primary topic.  This might be the closest http://www.danielpovey.com/files/2015_interspeech_aspire.pdf but it was about the aspire setup which is odd due to mismatch.   Generally ivectors help around 10% relative versus non-mean-normalized features, but less (maybe half of that) versus a baseline with CMN.  This is in matched conditions, where training and test are well matched.  Otherwise, there can be situations where ivectors will degrade performance.
