### ISSUE TITLE
Segments file end -1

### ISSUE THREAD

**Issue by ynop** [kaldi-asr/kaldi#3559]
The script kaldi/egs/wsj/s5/utils/validate_data_dir.sh does not allow a end of -1 for a segment.
According to the documentation and other tools (e.g. extract-segments) this should be allowed?

https://github.com/kaldi-asr/kaldi/blob/fcea01aa6984e54abb39c1b376434595489c6dbe/egs/wsj/s5/utils/validate_data_dir.sh#L166

**Comment by danpovey** [comment]
-1 is allowed by the binary but not by the scripts.  The reason is that
there are many scripts which need to work out the length of the segment
from the segments file, and having it not present there would cause
problems.  (E.g. imagine the scenario where some are -1 and some are not,
like if you combined directories.)
