### ISSUE TITLE
threadsafe

### ISSUE THREAD

**Issue by Xinyi7** [kaldi-asr/kaldi#3585]
Is nnet3 for x-vector extraction thread safe?

**Comment by danpovey** [comment]
You can do nnet3 operations from multiple threads safely if you are not using the GPU.  (Even if you are using the GPU it may actually be safe, IIRC, but maybe not optimal.)
The best way would be to batch up things from multiple utterances.  I wanted to create a `batched` version of the xvector computation based on the `batched` decoding that already exists... it would have computed xvectors from fixed-size chunks of utterances and averaged them, rather than computing them on the entire utterances.  (I don't think this would make any substantial difference.) . We didn't have time though.  I can forward some notes if you think you can do it.

**Comment by danpovey** [comment]
... but any specific object will, in general not be safe to use/call from multiple threads unless it is a const argument to any function-calls/constructors called from those threads.

**Comment by Xinyi7** [comment]
thank you
