### ISSUE TITLE
Running online demo in voxforge

### ISSUE THREAD

**Issue by cibin91** [kaldi-asr/kaldi#361]
hi,
-> I builded kaldi in Ubuntu
->I have to run a speech recognition online demo,which is in 
/egs/voxforge/online_demo
->I used ./run.sh --test-mode live ,to run demo
But it shows the following error
->./run.sh: line 57: online-gmm-decode-faster: command not found
        I already posted this question [https://github.com/kaldi-asr/kaldi/issues/347] ,you make some changes and asked me to pull the git .But it also doesnt work,the same error occurs.

**Comment by danpovey** [comment]
You have to do 'make ext' in src/.

**Comment by cibin91** [comment]
hi Dan,
   Thanks for the reply,
    The online demo is working now,thanks for helping

Cibin

**Comment by cibin91** [comment]
hi Dan,
   Its working, but the accuracy is too low
What i have to do to improve the accuracy(whether to change accent or to change any values)

Cibin

**Comment by danpovey** [comment]
That setup uses very out-of-date models (based on GMMs).  There are newer models based on neural nets but I don't think I should encourage you to try-- Kaldi is really intended for speech recognition professionals, and you need to have at least a minimal understanding of the technoglogy.
Please don't ask for help on the 'issues' threads - that is not what they are intended for, and Yenda has already warned you.

**Comment by eshete1972** [comment]
Hi All 
I  am working a speech recognition on my native language but at mono decoding HCLG.fst file can't be generated . Now I stop the experiment and the error is 
decode.sh: no such file /home/omar/kaldi/exp/System1/mono/graph/HCLG.fst
I need help to solve the problem.

**Comment by atiklt1972** [comment]
I am  a beginner for kaldi toolkit  and  I face a problem at mono phone training and decoding step. The problem  is listed below
ERROR: FstHeader::Read: Bad FST header: -
ERROR (fstpushspecial[5.4.105~1405-4fda]:ReadFstKaldi():kaldi-fst-io.cc:35) Reading FST: error reading FST header from standard input

[ Stack-Trace: ]

kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
fst::ReadFstKaldi(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
main
__libc_start_main
_start

ERROR: FstHeader::Read: Bad FST header: standard input
/home/tm/kaldi/steps/decode.sh --config conf/decode.config --nj 6 /home/tm/kaldi/exp/System1/mono/graph /home/tm/kaldi/data/test /home/tm/kaldi/exp/System1/mono/decode
decode.sh: no such file /home/tm/kaldi/exp/System1/mono/graph/HCLG.fst

how to solve the above problem especially the decoding problem.please help me.
    On Tuesday, April 24, 2018, 2:52:56 AM GMT+8, Daniel Povey <notifications@github.com> wrote:  
 
 
Likely there was an earlier error. See kaldi-asr.org/forums.html for how to ask questions, but you are not providing enough details, presumably the original error was on your screen earlier but you didn't see itl

**Comment by atiklt1972** [comment]
Hi All
I am a beginner for kaldi toolkit and I face a problem at mono phone training and decoding step. The problem is listed below
ERROR: FstHeader::Read: Bad FST header: -
ERROR (fstpushspecial[5.4.105~1405-4fda]:ReadFstKaldi():kaldi-fst-io.cc:35) Reading FST: error reading FST header from standard input

[ Stack-Trace: ]

kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
fst::ReadFstKaldi(std::__cxx11::basic_string<char, std::char_traits, std::allocator >)
main
__libc_start_main
_start

ERROR: FstHeader::Read: Bad FST header: standard input
/home/tm/kaldi/steps/decode.sh --config conf/decode.config --nj 6 /home/tm/kaldi/exp/System1/mono/graph /home/tm/kaldi/data/test /home/tm/kaldi/exp/System1/mono/decode
decode.sh: no such file /home/tm/kaldi/exp/System1/mono/graph/HCLG.fst

how to solve the above problem especially the decoding problem.please help me.
