### ISSUE TITLE
Need configure option to control run-time assertions

### ISSUE THREAD

**Issue by iskunk** [kaldi-asr/kaldi#3690]
As I understand it, the Kaldi source has assertions that can be enabled/disabled at compile time in one of three forms:

* Default: Some assertions are enabled

* `-DKALDI_PARANOID`: Enables additional, potentially CPU-intensive assertion checks (the [documentation](https://kaldi-asr.org/doc/error.html) currently states that this is enabled by default, but that does not appear to be the case)

* `-DNDEBUG`: Disables all assertions

This modality can have a significant impact on the operation of the resulting compiled libraries, and so an option for it ought to be present in the configure script, to facilitate its discovery and customization.

(Currently, `-DKALDI_PARANOID` is added in commented-out form to `kaldi.mk` without any description, and nothing is said about `NDEBUG`.)

**Comment by danpovey** [comment]
You're probably right.  You could perhaps add configure options?  If you have time?
@cloudhan it's something that could be considered for the CMake build as well.
@cloudhan, It just occurred to me that we need very clear and complete instructions for how to configure the CMake build, possibly in cmake/README.md.    The problem with CMake (versus our configure script) is that it's enormously harder to discover what the options are.

**Comment by iskunk** [comment]
I could submit a patch. Do you have any preferences for what such an option should be named?

(Side note: CMake is actually not bad about option discovery, if you make use of its GUI or ncurses frontends. Either will present a list of options, as well as a checkbox to hide/show an "advanced" subset. As far as I'm aware, it only lacks a command-line equivalent to `configure --help`.)

**Comment by danpovey** [comment]
Perhaps --debug-level N with N = 0, 1 or 2 and 1 being the default?

**Comment by iskunk** [comment]
I was, in fact, thinking along similar lines :-)  Let me get back to you on this...

**Comment by cloudhan** [comment]
For cmake, with `-DCMAKE_BUILD_TYPE=Release`, `NDEBUG` is automatically defined. Opt level is default to O3. There are other build types, e.g.,  `RelWithDebInfo` will build with debug symbol, `NDEBUG` is defined, Opt level is usually O2. These options is platform dependent, and I think they should go into the toolchain configuration as in [vpckg](https://github.com/microsoft/vcpkg/tree/master/scripts/toolchains).

Adding these definitions should be easy. All defs go into the top-level `CMakeLists.txt` will do the thing.

As for CMake usage, it is actually arcane due to its language design and the underlying sources to be built, that is, C++ libraries are usually harder to build compare to modern languages with unified/well-maintained build/package system. For basic CMake usage, I would argue, instead of educating users here, instruct them where to learn its usage is more helpful. [This section actually cover cmake's main use case.](https://llvm.org/docs/CMake.html#usage)

**Comment by iskunk** [comment]
I've submitted a PR with a proposed implementation. Please review, and let me know your thoughts.

**Comment by danpovey** [comment]
Addressed in #3690
