### ISSUE TITLE
request canceled while waiting for connection

### ISSUE THREAD

**Issue by computervisionlearner** [kaldi-asr/kaldi#3740]
Hello, my dear! When I pull the built image by instruction:
```
docker build --tag kaldiasr/kaldi:gpu-latest .
```
A error occurs, which shows:
```
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
What should I do to solve this problem??

**Comment by danpovey** [comment]
@mdoulaty  ?

**Comment by computervisionlearner** [comment]
Maybe I have solved this problem。
```
sudo vim /etc/systemd/system/docker.service.d/http-proxy.conf
```
and add your proxy information such as:
```
[Service] 
Environment="HTTP_PROXY=http://USER:PASSWD@server:PORT/"​
Environment="HTTPS_PROXY=http://USER:PASSWD@server:PORT/"
```
There are many reasons for this problem, the above is just one of the solutions。

**Comment by mdoulaty** [comment]
I guess no further action is needed from my side at the moment!
@computervisionlearner please let us know if you have further questions.
Also on a side note, you can use a prebuilt image as well, such as `kaldiasr/kaldi:gpu-latest` which is the latest daily build with GPU - or `kaldiasr/kaldi:gpu-2019-11` which is the GPU image of November 
unless you want to change something, then the easiest would be to simple use a prebuilt image rather than building an image yourself.
