### ISSUE TITLE
Build fails when making kaldi/src with configure --shared --use-cuda=no (docker and bare)

### ISSUE THREAD

**Issue by devspyrosv** [kaldi-asr/kaldi#3894]
Hello!)
I am using commit #743eb23d8 [egs] Added tri3b and chain training for Aurora4 (#3862)

When I try to build the docker image using a modified version of the provided Dockerfile the build fails during the last 2 make commands. 

The same thing happens if I try to build it in a clean Ubuntu 16.04 machine.

In order to reach this point I had to make some changes to the Dockerfile. 
In essence:

* I have added gfortran (by the way there is something wrong with the commit that fixes gfortran) and gawk.

* I copy srilm.tgz /opt/kaldi/tools/ .

* I use the multistage build technique to save some time (https://docs.docker.com/develop/develop-images/multistage-build/).

So when this point is reached: 
```
 cd /opt/kaldi/src && \
    ./configure --shared --use-cuda=no && \
    make depend -j 2 && \
    make -j 2
```
it fails with: 

```
g++ -M -std=c++11 -I.. -isystem /opt/kaldi/tools/openfst-1.6.7/include -O1 -Wno-sign-compare -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g -fPIC apply-batched-cmvn-online-cuda.cc compute-mfcc-online-batched-cuda.cc compute-online-feats-cuda.cc compute-online-feats-batched-cuda.cc compute-fbank-feats-cuda.cc compute-mfcc-feats-cuda.cc apply-cmvn-online-cuda.cc >> .depend.mk
compute-mfcc-online-batched-cuda.cc:18:31: fatal error: cuda_profiler_api.h: No such file or directory
 #include <cuda_profiler_api.h>
                               ^
compilation terminated.
../makefiles/default_rules.mk:149: recipe for target 'depend' failed
make[1]: *** [depend] Error 1
make[1]: Leaving directory '/opt/kaldi/src/cudafeatbin'
make: *** [cudafeatbin/depend] Error 2
make: *** Waiting for unfinished jobs....
Makefile:127: recipe for target 'cudafeatbin/depend' failed
make[1]: Leaving directory '/opt/kaldi/src/featbin'
The command '/bin/sh -c cd /opt/kaldi/src &&     ./configure --shared --use-cuda=no &&     make depend -j 2 &&     make -j 2' returned a non-zero code: 2
```

I believe that something is broken inside ```src/cudafeatbin/``` and more precisely in the Makefile existing there.

```src/cudafeatbin/Makefile``` has this conditional which seems to fail:

```
 ifeq ($(CUDA), true)
   BINFILES += compute-mfcc-feats-cuda apply-cmvn-online-cuda compute-online-feats-cuda compute-fbank-feats-cuda
 endif
```

Would anybody have  clue about this please?
Maybe would you kindly point me to a particular commit that should work?

Thank you very much!

**Comment by jtrmal** [comment]
you're right, I will fix
y.

**Comment by jtrmal** [comment]
Please pull and test

**Comment by devspyrosv** [comment]
It seems to work now. The build succeeded. Thank you! Thank you very much, indeed!

**Comment by jtrmal** [comment]
perfect, closing...

**Comment by devspyrosv** [comment]
I believe the last commits resurfaced the problem. 

I will stick to commit dce1dccd4.
At least for me, commit 134b1e918 does not compile and the same error is emitted.

**Comment by jtrmal** [comment]
I'll fix it today -- for some reason, this happens often
y.

**Comment by jtrmal** [comment]
should be fixed

**Comment by hackswitch** [comment]
~/kaldi/src$ configure –shared
configure: command not found

not sure what gives here.  
Kubuntu 20.04 and Kaldi

**Comment by hackswitch** [comment]
***() Installation of IRSTLM finished successfully
***() Please source the tools/extras/env.sh in your path.sh to enable it




> ~/kaldi/src$ configure –shared
> configure: command not found
> 
> not sure what gives here.
> Kubuntu 20.04 and Kaldi
----***() Installation of IRSTLM finished successfully
***() Please source the tools/extras/env.sh in your path.sh to enable it

May have missed this, not sure how to add. Thanks all!!

**Comment by nshmyrev** [comment]
@hackswitch it should be `./configure --shared`, not simply `configure --shared` with `./`

**Comment by jtrmal** [comment]
local directory is customarily not on path in unix/linux OSs
You have to call ./configure -- I'm pretty sure the readmes mention this
one way or another.
y.

**Comment by hackswitch** [comment]
yay! Thanks!
:~/kaldi/src$ ./configure --shared
Configuring KALDI to use MKL.
Checking compiler g++ ...
Checking OpenFst library in /home/ondine/kaldi/tools/openfst-1.6.7 ...
Checking cub library in /home/ondine/kaldi/tools/cub-1.8.0 ...
Doing OS specific configurations ...
On Linux: Checking for linear algebra header files ...
Configuring MKL library directory: Found: /opt/intel/mkl/lib/intel64
MKL configured with threading: sequential, libs: -L/opt/intel/mkl/lib/intel64 -Wl,-rpath=/opt/intel/mkl/lib/intel64 -lmkl_intel_lp64  -lmkl_core  -lmkl_sequential 
MKL include directory configured as: /opt/intel/mkl/include
Configuring MKL threading as sequential
MKL threading libraries configured as   -ldl -lpthread -lm
Using Intel MKL as the linear algebra library.
Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
Successfully configured for Linux with MKL libs from /opt/intel/mkl
WARNING: CUDA will not be used! If you have already installed cuda drivers
         and CUDA toolkit, try using the --cudatk-dir= option. A GPU and CUDA
         are required to run neural net experiments in a realistic time.
INFO: Configuring Kaldi not to link with Speex. Don't worry, it's only needed if
      you intend to use 'compress-uncompress-speex', which is very unlikely.
WARNING: slow expf() detected. expf() is slower than exp() by the factor of 1.10815
*** WARNING: expf() seems to be slower than exp() on your machine. This is a known bug in old versions of glibc. Please consider updating glibc. ***
*** Kaldi will be configured to use exp() instead of expf() in base/kaldi-math.h Exp() routine for single-precision floats. ***
Kaldi has been successfully configured. To compile:

  make -j clean depend; make -j <NCPU>

where <NCPU> is the number of parallel builds you can afford to do. If unsure,
use the smaller of the number of CPUs or the amount of RAM in GB divided by 2,
to stay within safe limits. 'make -j' without the numeric value may not limit
the number of parallel jobs at all, and overwhelm even a powerful workstation,
since Kaldi build is highly parallelized.
NUC7i5BNH:~/kaldi/src$

**Comment by mikatsukons** [comment]
when trying to install OpenBLAS by running extras/install_openblas.sh in a VM (ubuntu 18.04) I get a fail with this:


make[1]: Leaving directory '/home/mihaelakonstantinou/kaldi/tools/OpenBLAS/ctest'
make[1]: Entering directory '/home/mihaelakonstantinou/kaldi/tools/OpenBLAS/exports'
perl ./gensymbol linktest  x86_64 _ 0 0 0 0 0 0 "" "" 1 > linktest.c
cc -O2 -DMAX_STACK_ALLOC=2048 -DUSE_LOCKING -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DNO_WARMUP -DMAX_CPU_NUMBER=4 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.7\" -mavx2 -DASMNAME= -DASMFNAME=_ -DNAME=_ -DCNAME= -DCHAR_NAME=\"_\" -DCHAR_CNAME=\"\" -DNO_AFFINITY -I..  -shared -o ../libopenblas_haswell-r0.3.7.so \
-Wl,--whole-archive ../libopenblas_haswell-r0.3.7.a -Wl,--no-whole-archive \
-Wl,-soname,libopenblas.so.0 -lm -lgfortran -lm -lgfortran
/usr/bin/x86_64-linux-gnu-ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
Makefile:157: recipe for target '../libopenblas_haswell-r0.3.7.so' failed
make[1]: *** [../libopenblas_haswell-r0.3.7.so] Error 1
make[1]: Leaving directory '/home/mihaelakonstantinou/kaldi/tools/OpenBLAS/exports'
Makefile:101: recipe for target 'shared' failed
make: *** [shared] Error 2
make: Leaving directory '/home/mihaelakonstantinou/kaldi/tools/OpenBLAS'

could please anyone suggest what could have gone wrong?

**Comment by danpovey** [comment]
A question of finding the right package and apt-get installing it,
e.g. libgfortran4 or something like that, do `apt-cache search gfortran`
