### ISSUE TITLE
Errors that occur during code change

### ISSUE THREAD

**Issue by wanghaijin** [kaldi-asr/kaldi#3938]
I'm trying to implement ways to keep the model in memory and speed up the model. But when I change the nnet3-latgen-faster file in src/nnet3bin/,  an error occurred as shown in figure after swapping the running order of lines 136 and 138. I'm using the  [CVTE](http://www.kaldi-asr.org/models/2/0002_cvte_chain_model_v2.tar.gz)  model.
![image](https://user-images.githubusercontent.com/19617915/74736443-b2b08280-528d-11ea-83cc-f053fe9429cc.png)
![6P$D% }1(E{Z$A9ZVXM4Q9P](https://user-images.githubusercontent.com/19617915/74736323-71b86e00-528d-11ea-823b-b7e05cfcddb2.png)

**Comment by danpovey** [comment]
It's probably because the TableReader constructor spawns a process, which
UNIX does via fork(), so depending on your kernel memory settings
(overcommit_ratio, the amount of virtual memory, etc.), if you do fork() on
a process that has already allocated a lot of memory you can run out of
virtual memory and get killed.
