### ISSUE TITLE
Perhaps you have words missing in your lexicon?

### ISSUE THREAD

**Issue by gandolfxu** [kaldi-asr/kaldi#4019]
commit: b1d809386c17a9630d786b8fb0f67ed3bc173811
aishell/s5
default

ERROR:
ASSERTION_FAILED (compile-train-graphs[5.5.669~1-b1d80]:CompileGraphs():training-graph-compiler.cc:186) Assertion failed: (phone2word_fst.S    tart() != kNoStateId && "Perhaps you have words missing in your lexicon?")

**Comment by kkm000** [comment]
You did not provide enough information, and I am not equipped to run the recipe to reproduce; however, [the kaldi-help group had questions about aishell recently](https://groups.google.com/g/kaldi-help/search?q=aishell&sortBy=DATE), so I do not think that the problem is in the stock recipe. There must have been an error on one of previous steps that you probably missed.

I am closing this ticket for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it.
