### ISSUE TITLE
Can't checkout release 5.0 on Windows

### ISSUE THREAD

**Issue by nalbion** [kaldi-asr/kaldi#4070]
I thought that it might be an issue with Github actions not handling the branch name, but apparently the issue is with the file name:

> C:\Program Files\Git\bin\git.exe" checkout --progress --force -B 5.0 refs/remotes/origin/5.0
  ##[error]error: invalid path 'egs/babel/s5d/results/kws_results.104-pashto.flp.marcc2.conf.jtrmal1@jhu.edu.2016-03-31T11:34:24-04:00'
  ##[error]The process 'C:\Program Files\Git\bin\git.exe' failed with exit code 128

https://github.com/actions/checkout/issues/245

**Comment by kkm000** [comment]
@songmeixu, IMO, closing any but a clearly erroneously opened ticket deserves a couple words of  explaining of the reason why: as a rule, one of the main Kaldi tenets and strengths is the didactic value of its codebase, and it's always nice to stick to this idea as to extending it to communication patterns with its users.

@nalbion: The problem was the file names contained the `:`, which is not supported on Windows. The issue #1687 has been fixed 3+ years ago, in #1690.

Now, do you _really really_ have to use v5.0? Kaldi is a very fast-paced project, and v5.0 is stone-age-old by now. As a rule, we do not support old versions, except the last release and the current tip of the master (which is usually stable even for production use, from my own experience). If you cannot _reasonably_ upgrade, I see nothing wrong with backporting this fix to the 5.0 branch, the exceptional circumstances being the triviality of the fix.

All thighs considered, however, it's more likely than not makes sense for your app to use a later version of Kaldi. The API is generally stable, and if you find that something does not compile it's usually because an argument was added to a function--a trivial thing to fix, and we always comment the added arguments with instructive comments ("If your compile breaks at this call, ...."). We do not exert any effort into keeping backward-compatibility of the API (we only do for reading the persistent file formats), but generally, from practice, functions added often, but old signatures change rarely.

Branches 5.2 and later already contain the fix; I suggest switching to a later version of Kaldi, as recent one as possible. If that's a _reasonable_ hindrance, please respond to this ticket and **@ me** so that my phone bleeps and I do not miss it, and I'll transplant the fix to the 5.0 branch for you.  I'll keep the ticket closed unless I hear form you. And let me reiterate, we're understaffed so that we're extremely unlikely to be able to support less trivial issues in v5.0, should they hit you.
