### ISSUE TITLE
a flag to the configure script to enable a release/optimized build

### ISSUE THREAD

**Issue by lordadamson** [kaldi-asr/kaldi#4138]
I don't find a flag that I can pass to enable an `-O2` or `-O3`. I have to manually change that in the `kaldi.mk` or make some script that will make that change for me. The script can of course break very easily if `kaldi.mk` changes for any reason.

Would be nice if there was a way I could pass an option to remove the -g and put an `-O2`/`-O3`

**Comment by lordadamson** [comment]
I'm ready to work on a pull request if you find that to be a good idea.

**Comment by kkm000** [comment]
We already sorta have it: [set CXXFLAGS in the environment for our for `./configure](https://github.com/burrmill/burrmill/blob/a42a135ba/lib/build/kaldi/build_kaldi.sh#L46) and [pass them to make when compiling OpenFST](https://github.com/burrmill/burrmill/blob/a42a135ba/lib/build/kaldi/build_kaldi.sh#L139-L141). In either case, they are added after the default flags, therefore override them.

BTW, removing `-g` is almost never a good idea (unless you are compiling for a small device, where program size is a premium). The switch does not affect optimization, only [tells the compiler not to store symbol to address mapping and other information useful in a backtrace](https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/Debugging-Options.html#Debugging-Options). Even if you need to produce the smallest possible binaries, it's a usual practice to leave `-g`, and use strip(1) after the build passes all tests and right before release, otherwise failure diagnostics becomes much harder.

**Comment by lordadamson** [comment]
alright sounds good. Thanks :D
