### ISSUE TITLE
Build problems with recent -std=c++14 option in CUDA

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#4297]
There is some discussion here
 https://groups.google.com/d/msgid/kaldi-help/e4a7cc57-5c07-4888-9322-359f13589cb9n%40googlegroups.com.
e.g. with gcc 4.8.5 this didn't work.
we may have to update the configure script.

**Comment by kkm000** [comment]
What should we do: bump the minimum required compiler version unconditionally, or only if CUDA 11 is used? @danpovey, @jtrmal, what do you think?

GCC 4.8.5 was released June 23, 2015, 5.5 years ago.

**Comment by kkm000** [comment]
X-Ref: #4245

**Comment by jtrmal** [comment]
IMO would be fine to bump the version of the compiler unconditionally...
y.

**Comment by kkm000** [comment]
Looks like 4.8.5 comes with Centos 7. I never used it. Is it possible (and easy enough) to get a newer toolchain on that OS?

**Comment by jtrmal** [comment]
it might be, but people using centos7 will be probably very conservative,
so it might be significant obstacle
y.

**Comment by kkm000** [comment]
People using Sun Solaris are even more conservative. We need to draw the line somewhere.

**Comment by jtrmal** [comment]
I'm not arguing about that :)
y

**Comment by jtrmal** [comment]
actually, I'm not arguing at all :p
y.

**Comment by kkm000** [comment]
https://linuxize.com/post/how-to-install-gcc-compiler-on-centos-7/#installing-multiple-gcc-versions

**Comment by kkm000** [comment]
@jtrmal, what is the lowest Apple clang we need—do we need to bump it, too? I'll check gcc and LLVM clang, but I have no Mac.

**Comment by jtrmal** [comment]
this might help -- I'm not quite sure what would be the baseline:

https://trac.macports.org/wiki/XcodeVersionInfo

setting it to 10 or maybe 9 should be fine IMO
according to this
https://update.omnigroup.com/
most versions of macs are like three "releases" old at most
y.

**Comment by kkm000** [comment]
@jtrmal, I'm a Mac dummy. Is it correct to assume OS X does no longer occur in the wild, only macOS? Putting aside the branding name thing ("Mac OS X"/"OS X"/"macOS"; let's call it just OS), versions seem to be consistently increasing. The second link shows most up-to-date data up to OS 10.11, which is #6 in the order of seniority at the first link. Now I'm confused how to reconcile “three "releases" old at most” in your comment about the second link, which shows data for the sixth latest and earlier releases. How do you define a "release" then?

**Comment by jtrmal** [comment]
yeah, I'm perhaps calling it incorrectly -- I'm just using the mac as a HW
terminal to log somewhere else...
But I think we can consider everything after 10.12 as ancient, I believe. I
didn't realize the second link contains data so old.
y.

**Comment by kkm000** [comment]
@jtrmal I found [this table, which lists C++14 compilers](https://github.com/jinja2cpp/Jinja2Cpp#supported-compilers) required to build some unrelated software. With this, I think I'm good to go!

**Comment by jtrmal** [comment]
yes, looks good

**Comment by hugovbraun** [comment]
@kkm000 did you end up bumping the minimum required compiler version unconditionally? Wondering if we could have the cpu code compiled with C++14 as well

**Comment by kkm000** [comment]
Right on my list. I already RFC on kaldi-users and bumped up the message for 2 weeks, and no one objected. Besides, we sorely need C++14 features in the main codebase. No issues whatsoever. I'm using Cuda 11.2 with C++17, which is even stricter. We should thank @jtrmal for this—he kept the codebase compilable even with C++20, nee C++2x.

I am just completely deprived of free cycles. Incidentally, @hugovbraun, I'm integrating your GPU decoder into a real-word product. Thanks for it, I never seen anything under Kaldi pegging the GPU at 100%. I'd appreciate if I could be able to contact you in case of emergency, if I run into issues—but the Issues here are not for questions (as a maintainer, I shoo away and to kaldi-help the users who are asking questions instead of reporting issues , and can't thus except myself), and kaldi-help does not seem an appropriate venue, as you probably do not actively monitor it. If you do not mind me bothering you, what do you think would be the best way?

I have a little patch that makes the decoder compile on Windows, where I also replaced the sesuipedalian #defines with const integral types. Would appreciate if you could review it.

Well, come think of it, I should just do it. Ok, hold my beer...

**Comment by kkm000** [comment]
X-ref: https://groups.google.com/g/kaldi-help/c/DkoacGpwGJ4/m/Zgj78rgfAgAJ
