### ISSUE TITLE
Sporadic timeouts when downloading sctk tools

### ISSUE THREAD

**Issue by markus-franke** [kaldi-asr/kaldi#4311]
When building Kaldi we sometimes get download timeouts for SCTK in the tools folder.

```
Unable to establish SSL connection.
make: *** [Makefile:124: sctk-2.4.10-20151007-1312Z.tar.bz2] Error 4
make: *** Waiting for unfinished jobs....
Unable to establish SSL connection.
```

The current timeout is set to 10 seconds (see snippet below).

**tools/Makefile:124**
```
sctk-$(SCTK_VERSION).tar.bz2:
	if [ -d "$(DOWNLOAD_DIR)" ]; then \
		cp -p "$(DOWNLOAD_DIR)/sctk-$(SCTK_VERSION).tar.bz2" .; \
	else \
		$(WGET) -T 10 https://www.openslr.org/resources/4/sctk-$(SCTK_VERSION).tar.bz2; \
	fi
```

Increasing the timeout to e.g. 20 seconds leads to a successful download and build afterwards.

Wouldn't it make sense to increase those timeouts in general to avoid sporadic timeouts for slow endpoints?

**Comment by slckl** [comment]
I'm also seeing kaldi builds fail because of this, but I'm not sure if 20 seconds will cut it. 
It seems the openslr resources get hammered more at certain times of day, which makes Kaldi builds unpleasantly flaky, particularly because it doesn't fail the whole build as soon as this download fails, at least with -j4.

**Comment by danpovey** [comment]
I am tuning the apache config on openslr to hopefully make it more stable.

**Comment by kkm000** [comment]
They're officially on GitHub now, so we can pull the tarball from there.

**Comment by kkm000** [comment]
I'm changing the makefile to pull SCTK from GitHub.
