### ISSUE TITLE
Hang in train_one_epoch () -> get_validation_objf() -> get_objf()  -> criterion()

### ISSUE THREAD

**Issue by cding-nv** [kaldi-asr/kaldi#4346]
Hi 
    Can you give some suggestions?

**Env:**
  Branch:  origin/pybind11   commit: 1c573b39899acd90a3d4cf4e8b5284f3a5deb6ef
  pytorch version:  nvcr.io/nvidia/pytorch:19.06-py3
  nvidia driver:  NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0 

**Training case:**
     egs/aishell/s10
     ./local/run_chain.sh --stage 21

**Result:**
   Single machine and one V100 gpu is successful for tdnn pytorch training, about 31minutes, sm%~80% mem%~40%
   what's change:   num_workers = 1   and  "queue.pl to run.pl"
   **But Single machine and 4 V100 GPUs is failed.**

**Issue:**
   Rank 0 need "valid_dataloader". It hangs in 
      "train_one_epoch () ->  get_validation_objf() ->   get_objf()  -> criterion()"
   Rand 1, 2, 3 don't need "valid_dataloader".
   **GPU 0, 1, 2, 3 sm% all are 100%**
   what's change: num_workers = 4 ,  device_ids="0, 1, 2, 3"

**Comment by danpovey** [comment]
@csukuangfj any ideas?

**Comment by csukuangfj** [comment]
@qindazhu  could you give any help? Initially, there was only DDP (distributd data parallel). I guess queue.pl and run.pl were
added by you.

**Comment by qindazhu** [comment]
I suppose you have set your local GPUs to `exclusive mode`.

Did you run the data preparation steps separately for the two experiments (single machine with `num_workers == 1`, and  single machine with `num_workers == 4`)?   For DDP training with `num_works > 1`, we have to make sure each work load the same number of batches (we did this in https://github.com/kaldi-asr/kaldi/blob/1c573b39899acd90a3d4cf4e8b5284f3a5deb6ef/egs/aishell/s10/local/run_chain.sh#L194), otherwise they may wait to sync with each other and the program will hang.

So try to delete all local data and run from beginning of run_chain to see if you still have the issue. Let me know if it does not work.

**Comment by cding-nv** [comment]
>> I suppose you have set your local GPUs to exclusive mode
Yes.

>> Did you run the data preparation steps separately for the two experiments 
Yes.

I will delete all local data and try again. Thanks for the quick reply.

**Comment by kkm000** [comment]
@cding-nv, is this resolved?

**Comment by cding-nv** [comment]
Resolved. Thanks.

**Comment by kkm000** [comment]
Thanks for letting me know!
