### ISSUE TITLE
failed while run extras/install_mkl.sh

### ISSUE THREAD

**Issue by plll4zzx** [kaldi-asr/kaldi#4394]
The following packages were automatically installed and are no longer required:
  aptitude-common atril-common bubblewrap debugedit engrampa-common fonts-mathjax gconf-service gconf-service-backend
  gconf2 gconf2-common libatkmm-1.6-1v5 libbonobo2-0 libbonobo2-common libbonoboui2-common libboost-iostreams1.58.0
  libbrotli1 libburn4 libcwidget3v5 libexo-common libexo-helpers libgarcon-common libgconf-2-4 libglibmm-2.4-1v5
  libgnome-keyring-common libgnome-keyring0 libgnome2-common libgnomecanvas2-common libgnomeui-common libgnomevfs2-0
  libgnomevfs2-common libisofs6 libjpeg-turbo-progs libjs-mathjax libjte1 liblightdm-gobject-1-0 liblua5.2-0
  liboobs-1-5 liborbit-2-0 librpm8 librpmbuild8 librpmio8 librpmsign8 libsigc++-2.0-0v5 libsqlite0 libtagc0
  libtumbler-1-0 liburl-dispatcher1 libutempter0 libwnck-common libwoff1 libxapian22v5 libxfce4ui-common
  libxfce4util-bin libxfce4util-common libxfce4util7 libxfconf-0-2 mate-calc-common mate-desktop-common onboard-common
  p7zip p7zip-full python-iniparse python-libxml2 python-lzma python-rpm python-sqlite python-sqlitecachec
  python3-dateutil python3-psutil python3-xcffib rpm rpm-common rpm2cpio system-tools-backends thunar-data
  tumbler-common xdg-desktop-portal xfce4-power-manager-data xfconf xfdesktop4-data xubuntu-icon-theme
  xubuntu-wallpapers
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  apt
The following NEW packages will be installed:
  apt-transport-https
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  apt
0 upgraded, 1 newly installed, 1 to remove and 3 not upgraded.
E: Essential packages were removed and -y was used without --allow-remove-essential.
extras/install_mkl.sh: MKL package intel-mkl-64bit-2020.0-088 installation FAILED.

Please open an issue with us at https://github.com/kaldi-asr/kaldi/ if you
believe this is a bug.

**Comment by puneetbawa** [comment]
Not enough info. I think the issues are with some internal packages of the system. For more details you can refer to thread #4159

**Comment by plll4zzx** [comment]
after clone kaldi and extras/check_dependencies.sh, it told me to install MKL, then I face this situation. I also try to install MKL just from Intel's website, but nothing changed, the output of extras/check_dependencies.sh and extras/install_mkl.sh are stay still.

**Comment by kkm000** [comment]
The immediate cause of failure is that `apt` tries to remove itself, finds that it has not obtained your permissions in a form of the command line flag, and aborts the whole install. But the proximate cause (`apt` should not normally annihilate itself, right?) is a broken state of your package database. I've never seen `apt` trying to do the seppuku, and the fact that it does means something.

I did not go through the long list of libraries that it want to autoremove, so do not follow this advice blindly, but first of all, tell `apt` he's a good boy and has no reason to commit suicide:
```
sudo apt install apt
```
This command looks weird, but makes sense. since `apt` is already installed, but only as a dpendency of a package which is no longer exists, it will be marked as "manually installed", and will always be available as a deb package manager. So this command does not install anything, it just protect `apt` from harakiri. You've probably experimented with package managers too much (judging by apt's desire to take aptitude to the other bank of Lethe with it). It's a totally correct state of `apt`: it cannot be installed except than manually, otherwise to install apt you need to manually install `apt` first, but... uoi see the point.

After you cure `apt` of suicidal ideation, manually check whether you really need any of the packages it's going to uninstall automatically. If in doubt, use
```
$dpkg -s atril-common  # What is the package 'atril-common' for, and what's it's dependencies? (the `Depends:` line)
$dpkg -L atril-common  # What files are in the package 'atril-common'?
$dpkg -S `which git`  # From which package the executable `git` came? (same for libraries. Use full path if ambiguous).

**Comment by yb-huang** [comment]
I want to know how to deal with this:
when I run extras/check_dependencies.sh , the system told me to run extras/install_mkl.sh
but when I run extras/install_mkl.sh , the system told me MKL version 3 is already installed.
