### ISSUE TITLE
cuda version 

### ISSUE THREAD

**Issue by shanhaidexiamo** [kaldi-asr/kaldi#4402]
Hi, I want to make sure that whether kaldi support cuda11?

**Comment by danpovey** [comment]
yes

**Comment by kkm000** [comment]
I'm closing this issue, because it is a question, not a feature proposal or a defect report. **We have a forum that is the best place to ask questions**, and getting answers and input from other users as well. We are hanging out there all the time, too. Here, in the issue tracker, we are just too few.

**Kaldi help forum**: https://groups.google.com/forum/#!forum/kaldi-help

**Instructions for joining**: http://kaldi-asr.org/forums.html

If you think I misunderstood your intention, please reply, and I'll reopen it.
