### ISSUE TITLE
Phone recognition level

### ISSUE THREAD

**Issue by FirasHm** [kaldi-asr/kaldi#4439]
Hello, thank you very much for this great tool! I would like to use Kaldi for phoneme recognition (only get the acoustic model outputs). Do you have some ideas or ideally which command should I use?
Thanks in advance

**Comment by kkm000** [comment]
I'm closing this issue, because it is a question, not a feature proposal or a defect report. **We have a forum that is the best place to ask questions**, and getting answers and input from other users as well. We are hanging out there all the time, too. Here, in the issue tracker, we are just too few.

**Kaldi help forum**: https://groups.google.com/forum/#!forum/kaldi-help

**Instructions for joining**: http://kaldi-asr.org/forums.html

If you think I misunderstood your intention, please reply, and I'll reopen it.
