### ISSUE TITLE
Train New Model With Few New Audio and Words

### ISSUE THREAD

**Issue by raditya-fajar** [kaldi-asr/kaldi#4459]
Hello,
I'm on my project to build own ASR module which can used realtime transcription and can init new training process on the fly, let's say, i can upload one or more new audio file and it's words. How i can achieve this?

I have my own nnet3 model trained with my own data set before, then i want keep train these models overtime, on-the-fly, without start the process from begining.

Thank you

**Comment by kkm000** [comment]
I'm closing this issue, because it is a question, not a feature proposal or a defect report. **We have a forum that is the best place to ask questions**, and getting answers and input from other users as well. We are hanging out there all the time, too. Here, in the issue tracker, we are just too few.

**Kaldi help forum**: https://groups.google.com/forum/#!forum/kaldi-help

**Instructions for joining**: http://kaldi-asr.org/forums.html

If you think I misunderstood your intention, please reply, and I'll reopen it.
