### ISSUE TITLE
Questions about HCLG.txt converted from HCLG.fst

### ISSUE THREAD

**Issue by YizhengZhang** [kaldi-asr/kaldi#4471]
Hello! I ran the timit example in kaldi and got the HCLG.fst for tri3 model. When I browsed the HCLG.txt converted from HCLG.fst using fstprint, I found the weights of some arcs were missing (The weight of the fourth row is missing in the picture below.). Does this mean that the weights of these arcs are zero? 
![image](https://user-images.githubusercontent.com/48672855/110274535-ff3a3d80-8009-11eb-9e36-516e47ea730c.png)

**Comment by danpovey** [comment]
Yes.

**Comment by YizhengZhang** [comment]
Thank you!

**Comment by kkm000** [comment]
I'm closing this issue, because it is a question, not a feature proposal or a defect report. **We have a forum that is the best place to ask questions**, and getting answers and input from other users as well. We are hanging out there all the time, too. Here, in the issue tracker, we are just too few.

**Kaldi help forum**: https://groups.google.com/forum/#!forum/kaldi-help

**Instructions for joining**: http://kaldi-asr.org/forums.html
