### ISSUE TITLE
Code Error: length > utt-length while performing speaker verification task for my own dataset. 

### ISSUE THREAD

**Issue by Pranavk02** [kaldi-asr/kaldi#4528]
My dataset contains shorter utterances and for the speaker verification task(low-resource language), I had split my test utterances for 1sec and 2sec. 
Can you please help me in providing a feasible solution concerning the same? 
```
sid/nnet3/xvector/allocate_egs.py --prefix train_subset --num-repeats=1 --min-frames-per-chunk=200 --max-frames-per-chunk=400 --randomize-chunk-length false --frames-per-iter=100000 --num-archives=3 --num-jobs=1 --utt2len-filename=exp/xvector_nnet_1a/egs/temp/utt2num_frames.train_subset --utt2int-filename=exp/xvector_nnet_1a/egs/temp/utt2int.train_subset --egs-dir=exp/xvector_nnet_1a/egs
['sid/nnet3/xvector/allocate_egs.py', '--prefix', 'train_subset', '--num-repeats=1', '--min-frames-per-chunk=200', '--max-frames-per-chunk=400', '--randomize-chunk-length', 'false', '--frames-per-iter=100000', '--num-archives=3', '--num-jobs=1', '--utt2len-filename=exp/xvector_nnet_1a/egs/temp/utt2num_frames.train_subset', '--utt2int-filename=exp/xvector_nnet_1a/egs/temp/utt2int.train_subset', '--egs-dir=exp/xvector_nnet_1a/egs']
Processing archive 1
Ran out of speakers for archive 1
Processing archive 2
Ran out of speakers for archive 2
Processing archive 3
code error: length > utt-length
# Accounting: time=0 threads=1
# Ended (code 1) at Thu May 13 14:44:25 IST 2021, elapsed time 0 seconds
```

**Comment by puneetbawa** [comment]
In such kind of short utterance scenarios, you can change for the values of min frames per chunk=150 and max frame per chunk=250 instead of --min-frames-per-chunk=200 --max-frames-per-chunk=400. 

i hope this might be useful?

**Comment by kkm000** [comment]
I'm closing this issue, because it is a question, not a feature proposal or a defect report. **We have a forum that is the best place to ask questions**, and getting answers and input from other users as well. We are hanging out there all the time, too. Here, in the issue tracker, we are just too few.

**Kaldi help forum**: https://groups.google.com/forum/#!forum/kaldi-help

**Instructions for joining**: http://kaldi-asr.org/forums.html

If you think I misunderstood your intention, please reply, and I'll reopen it.
