### ISSUE TITLE
Is it possible to use Checkpoints during TDNN kaldi training?

### ISSUE THREAD

**Issue by yilmazay74** [kaldi-asr/kaldi#4536]
Hi,
I wonder if there is any way to put checkpoints during TDNN kaldi training,
so that , if somehow an error occurs at some point, we can rollback to a safe checkpoint and continue from there on,
instead of starting the training iterations from scratch.
I am using nnet3 type DNN training setup.
We are running this training on AWS using 4 paralel Nvidia V100 type GPUs.
Approximately it takes around 2 days for training, and more than 30 hours is spent in train.py iterations.
Currently it makes around 2500 iterations for tdnn training.
So, when an error occurs, sometimes hours of training are being lost.
So, I thought if there had been some kind of checkpoints for lets says for every 100 or 500 hundred iterations,
this way we would not be loosing all the training work done so forth.
Any light or suggestions on this subject will be much appreciated.
REgards
Y.A

**Comment by danpovey** [comment]
Yes it supports that already, you can start from any iteration, depending
what script you are using it can be accomplished with a combination of
--stage (e.g. 6, depends
where it calls train.py) and --train-stage (give the last model it
successfully wrote, I think).

**Comment by yilmazay74** [comment]
Hi Daniel,
For the stage checkpoint, yes I know that. 
train-stage, it is set as -10 in train.py.
I guess that means, do it from scratch.
Regarding your suggestion, (please excuse my ignorance) , what should I set  the --train-stage as ?
in your post, you said that 'give the last model it successfully wrote', however, since the training is not finished yet, the model is not generated yet.
Do you mean any temporary directory that the tempoary model files are written in?
In that case, which directory is it?

Best Regards
Y.A.

**Comment by kkm000** [comment]
I'm closing this issue, because it is a question, not a feature proposal or a defect report. **We have a forum that is the best place to ask questions**, and getting answers and input from other users as well. We are hanging out there all the time, too. Here, in the issue tracker, we are just too few.

**Kaldi help forum**: https://groups.google.com/forum/#!forum/kaldi-help

**Instructions for joining**: http://kaldi-asr.org/forums.html

If you think I misunderstood your intention, please reply, and I'll reopen it.
