### ISSUE TITLE
Translating bash recipes to python

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#455]
We are trying to test the feasibility of having python recipes in kaldi without requiring major modifications to the core scripts in utils. As a test we would like to translate steps/nnet3/lstm/{train,decode}.sh.

**Comment by vdp** [comment]
FWIW, I have ambivalent feelings about this.. IMHO, there is a certain virtue in using Bash at script level. Being such an atrociously inadequate language(most of the time it feels to me more like a pile of random hacks, rather than a product of intelligent design), Bash forces the developer to keep the things simple at the script level and to think harder how to make the binaries more self-contained and complementary to each other. (I guess we can say that Bash acts as a sort of "regularizer", keeping the script complexity low). On the other hand my Python scripts often end up being a convoluted mess, exactly because Python is such a wonderful and intuitive language, which allows me to start "hacking" without a clear idea about the structure of the code.
Then again, I don't know, maybe the scripts will become nicer, especially if there are clear guidelines about what can and can't be implemented at script level(e.g. resist the temptation to move core stuff to Python).
Just my $0.02..

**Comment by vijayaditya** [comment]
The idea is to still rely on the binaries for all the heavy lifting. The recipes are also still going to heavily rely on bash due to the parallelization it affords e.g. using pipes to connect individual processes. So think of a python script which launches a series of shell commands (each composed of many binaries connected with pipes). Further even simple things like file searches are far faster using grep compared to regex library in python, so the reliance on shell is inevitable.

In my opinion, the main goals of the current translation effort is
1.  to improve readability of the scripts by making proper use of 
2.  to have more informative exceptions and better exception handling in the scripts

Another advantage of the translation is better debugging capabilities using tools like <code>pdb</code> rather than relying on <code>set -ex </code>.

**Comment by danpovey** [comment]
We're just going to try writing one script in python for now and see how it
turns out.
The script will still be structured the same way as a bash script would,
and will be self contained.
Dan

**Comment by vdp** [comment]
I see, thanks! 
It would be definitely interesting to compare the look&feel of Python- vs Bash-based recipes (or part of recipes as I understand it will be in this case). In the past some people on the mailing list have expressed their support for something like this, so I guess it's worth trying.

**Comment by vijayaditya** [comment]
see #490
