### ISSUE TITLE
ivector-plda-scoring-dense.cc: Code terminated with exit code 139 for a recording with ~75,000 i-vectors

### ISSUE THREAD

**Issue by rahulshivajipawar** [kaldi-asr/kaldi#4555]
1) ivector-plda-scoring-dense binary exits with code 139 for a recording with ~75,000 i-vectors. 
2) This runs successfully for much lower values of i-vectors in a recording. 
3) The log is not very informative as well. 

Log:

ivector-plda-scoring-dense --target-energy=0.1 plda ark:spk2utt 'ark:ivector-subtract-global-mean mean.vec scp:feats.scp ark:- | transform-vec transform.mat ark:- ark:- | ivector-normalize-length ark:- ark:- |' ark,scp:scores.1.ark,scores.1.scp 
transform-vec transform.mat ark:- ark:- 
ivector-normalize-length ark:- ark:- 
ivector-subtract-global-mean mean.vec scp:feats.scp ark:- 
LOG (ivector-subtract-global-mean[5.5.7091-75872]:main():ivector-subtract-global-mean.cc:108) Wrote 74859 mean-subtracted iVectors
LOG (transform-vec[5.5.7091-75872]:main():transform-vec.cc:85) Applied transform to 74859 vectors.
LOG (ivector-normalize-length[5.5.7091-75872]:main():ivector-normalize-length.cc:90) Processed 74859 iVectors.
LOG (ivector-normalize-length[5.5.7091-75872]:main():ivector-normalize-length.cc:94) Average ratio of iVector to expected length was 0.874948, standard deviation was 0.105611
 Accounting: time=10 threads=1
 Ended (code 139) at Thu Jun  3 01:59:56 CDT 2021, elapsed time 10 seconds

**Comment by kkm000** [comment]
@danpovey, does it look like anything you have seen?

I would not say that the log is not at all informative, although, hard to disagree, it could have been better.

Exit code 139 is a segfault (128 + 11 = SIGSEGV).

At least I can read that _most likely_ the input pipeline to `ivector-plda-scoring-dense` completed successfully (all pipeline programs wrote the final messages; they could segfault on exit as well, but that's less probable). Without a debugger attached or a core file, it's nearly impossible to track this down further.

Can you run the command on your own machine, or on the same cluster interactively, if you have gdb there? basically, you need all input files (`plda`, `spk2utt`, `mean.vec`, `transform.mat`, `feats.scp`; then make sure that the features pointed to by `feats.scp` are accessible (they are likely on the NFS shared partition, since that's a cluster log): just look into that file with `head feats.scp` and see where it points to, and try to `ls -lr` that location. Make sure that Kaldi is built with debug symbols (`-g`) and low optimization (`-O0` ideal, `-O1` okay). Then run it using gdb's `r` command:
```
gdb --args ivector-plda-scoring-dense --target-energy=0.1 plda ark:spk2utt 'ark:ivector-subtract-global-mean mean.vec scp:feats.scp ark:- | transform-vec transform.mat ark:- ark:- | ivector-normalize-length ark:- ark:- |' ark,scp:scores.1.ark,scores.1.scp
. . .
(gdb) r
```
When it segfaults, extract the backtrace with the `bt` command:
```
Signal 11 (SIGSEGV) caught at ....
(gdb) bt
```
Post it here if you do not see why it crashed. Or make a PR to propose a fix. :)

**Comment by kkm000** [comment]
BTW, I do not see the SHA `7091` on the Kaldi's master. Have you modified it, and if those are just script commits or something, how old are the sources? Maybe all you need a fresher Kaldi.

**Comment by kkm000** [comment]
Another possible reason, on the cluster you may be simply running out of memory. If you cut a slice of 1/10 of the feats.scp and it goes through, play with its size.

**Comment by kkm000** [comment]
I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!
