### ISSUE TITLE
ERROR (compute-mfcc-feats[5.5.935~1-27191]:Read():wave-reader.cc:122) WaveData: expected RIFF or RIFX, got 

### ISSUE THREAD

**Issue by Manasmalhotra** [kaldi-asr/kaldi#4581]
[make_mfcc_train.1.log](https://github.com/kaldi-asr/kaldi/files/6700590/make_mfcc_train.1.log)
![error4](https://user-images.githubusercontent.com/42417319/123073562-24757f00-d434-11eb-909e-d8e61224d441.png)
![error3](https://user-images.githubusercontent.com/42417319/123073571-25a6ac00-d434-11eb-9bb5-12d6fcae0f60.png)
![error2](https://user-images.githubusercontent.com/42417319/123073576-26d7d900-d434-11eb-8978-b7ce01a2aa40.png)

**Comment by Manasmalhotra** [comment]
I am new to kaldi and was trying to execute the scripts provided in the following tutorial,but getting the audio accessibility errors for the first time. I have debugged my code in this stage earlier also but  have not got this error anytime.
Not able to understand whats the problem. Please help.

**Comment by Manasmalhotra** [comment]
Link - https://www.eleanorchodroff.com/tutorial/kaldi/training-acoustic-models.html#prepare-directories

**Comment by kkm000** [comment]
With the truncated error message, no idea. Maybe one of the files is broken.

I'm closing this issue, because it is a question, not a feature proposal or a defect report. **We have a forum that is the best place to ask questions**, and getting answers and input from other users as well. We are hanging out there all the time, too. Here, in the issue tracker, we are just too few.

**Kaldi help forum**: https://groups.google.com/forum/#!forum/kaldi-help

**Instructions for joining**: http://kaldi-asr.org/forums.html

If you think I misunderstood your intention, please reply, and I'll reopen it.
