### ISSUE TITLE
online2-wav-nnet2-latgen-faster.cc from microphone 

### ISSUE THREAD

**Issue by GFortet** [kaldi-asr/kaldi#4582]
Good morning,
I am currently trying to implement an online from microphone with portaudio version of **online2-wav-nnet2-latgen-faster.cc**
At the moment **online-gmm-decode-faster.cc** works well on my device. So i would like to modify **online2-wav-nnet2-latgen-faster.cc** so it works in a similar way.

I was thinking about modifying the class Wavreader to make it read from the microphone but i don't know if it is the best solution. Any idea or suggestion ?

**Comment by kkm000** [comment]
online2-wav-nnet2-latgen-faster.cc internally uses OnlineNnet2FeaturePipelineInfo which accepts raw audio, and this is what you should use in _your own_ program. When using Kaldi in production, always write your own binaries. The audio format is a SubVector (and Vector also derives from SubVector) of floating point samples, each with the value range ±32768.0 for 0dB, for historical reasons (erstwhile HTK compat), i.e. not normalized to ±1.0 as it's done in many audio applications.

Read the binary's code as an example, but RYO. The binary *simulates* online decoding of a whole bunch of *files* read from wav.scp and clocks them in the stream time as if it were real time. Decoding is online, the binary isn't. It's designed for decoding and benchmarking in recipe scripts, which always operate on test sets, not for real-life use.

BTW, why nnet2 and not nnet3 CTC "chain" model? You mentioned "device", and nnet3 is much more compact (it uses trivial H topology and bigrams, so that the NN outputs are by far fewer, like 5000 vs. 60000 for a large model), and about 10 times faster to compute, because of both this fact and 3× undersampling in the decoder) to hit about same WER. Both are critically important if the "device" is a smartphone or Pi level CPU. Note that online2/ is for both online pipelines with the nnet2 and nnet3 models (i.e., do not look for "online3/" for nnet3 :) ). Look at online2-wav-nnet3-latgen-faster.cc.
