### ISSUE TITLE
compute GOP of my own wav voice record

### ISSUE THREAD

**Issue by omidaghdaei** [kaldi-asr/kaldi#4584]
Hi
How can I give my own wav voice record and compute it's GOP???
I've searched in documents in Kaldi site but didn't find anything about it.
I want to know that is there any way that get my wav voice and compute it's GOP or not?

**Comment by kkm000** [comment]
I'm closing this issue, because it is a question, not a feature proposal or a defect report. **We have a forum that is the best place to ask questions**, and getting answers and input from other users as well. We are hanging out there all the time, too. Here, in the issue tracker, we are just too few.

**Kaldi help forum**: https://groups.google.com/forum/#!forum/kaldi-help

**Instructions for joining**: http://kaldi-asr.org/forums.html

If you think I misunderstood your intention, please reply, and I'll reopen it.
