### ISSUE TITLE
fstpushspecial: error while loading shared libraries: fstpushspecial: unsupported version 0 of Verneed record

### ISSUE THREAD

**Issue by Manasmalhotra** [kaldi-asr/kaldi#4585]
I have been trying to run the scripts from kaldi for dummies tutorial but am encountering the error mentioned above.
I have tried the below attached method to use the shared libraries effectively but not been able to resolve the issue.
Please look into it!!

![ERROR2](https://user-images.githubusercontent.com/42417319/123755437-85400400-d8d9-11eb-9720-41235850b654.png)
![ERROR](https://user-images.githubusercontent.com/42417319/123755441-86713100-d8d9-11eb-9a69-2187f2062493.png)

**Comment by galv** [comment]
Try `ldd $(which fstpushspecial)`. Your error message is bizarre. I suspect stdout and stderr are being mixed together in your current output.

**Comment by Manasmalhotra** [comment]
> Try `ldd $(which fstpushspecial)`. Your error message is bizarre. I suspect stdout and stderr are being mixed together in your current output.

I think you meant ldd $(which fstpushspecial) run.sh. It's giving output as not a dynamic executable.
have tried sudo apt-get install gcc-multilib but still the same output.

**Comment by kkm000** [comment]
I'm closing this issue, because it is a question, not a feature proposal or a defect report. **We have a forum that is the best place to ask questions**, and getting answers and input from other users as well. We are hanging out there all the time, too. Here, in the issue tracker, we are just too few.

**Kaldi help forum**: https://groups.google.com/forum/#!forum/kaldi-help

**Instructions for joining**: http://kaldi-asr.org/forums.html

If you think I misunderstood your intention, please reply, and I'll reopen it.
