### ISSUE TITLE
errors in aishell2 finetune script 

### ISSUE THREAD

**Issue by Asma-droid** [kaldi-asr/kaldi#4593]
Hi all, 

I think that the problem reported in #4065 is not yes corrected.

Actually, i have used the mini_librispeech code for training model from scratch. and i have then used the aishell2 fine tune code. I have faced the same problem as that reported in #4065

```
LOG (nnet3-am-train-transitions[5.5.929~1539-9bca2]:main():nnet3-am-train-transitions.cc:131) Setting priors of pdfs in the model.
ASSERTION_FAILED (nnet3-am-train-transitions[5.5.929~1539-9bca2]:SetPriors():nnet3-am-train-transitions.cc:32) Assertion failed: (tmodel.NumPdfs() == am_nnet->NumPdfs())
```

**Comment by kkm000** [comment]
`9bca2` is current. Interesting. Could you post the full command line (the whole pipeline at the start of log file)?

**Comment by Asma-droid** [comment]
I'am using the last kaldi version.

Please find attached the log file as well as the finetune code. I have juste replace make_mfcc_pitch by make_mfcc (the only change made)
[fine_tune_code.txt](https://github.com/kaldi-asr/kaldi/files/6854167/fine_tune_code.txt)


[init_mdl.log](https://github.com/kaldi-asr/kaldi/files/6854148/init_mdl.log)

**Comment by kkm000** [comment]
Look at the first log line:
```
nnet3-am-init exp/dev_clean_ali/final.mdl exp/chain/tdnn1j_sp_online_dev_clean/input.raw - | nnet3-am-train-transitions ....
```
`nnet3-am-init` takes the transition model (TM) and raw nnet (NN), combines into one file and passes iton to nnet3-am-train-transitions. nnet3-am-train-transitions dies because NN output dimension does not equal the number of PDFs in the TM.

**What is likely went wrong**: the TM in `exp/dev_clean_ali/final.mdl` does not match the raw NN in `exp/chain/tdnn1j_sp_online_dev_clean/input.raw`. Confirm that by comparing the number of PDFs in the TM reported by
```
am-info exp/dev_clean_ali/final.mdl
```
to the output dim of the NN reported by (note spaces in fgrep)
```
nnet3-info --print-args=false exp/chain/tdnn1j_sp_online_dev_clean/input.raw | fgrep  ' name=output '
```
I'm nearly certain you'll see a mismatch. I can't imagine where else it could come from. Please let me know if that was it.

If so, we should have caught that in `nnet3-am-init` but did not.

**Comment by Asma-droid** [comment]
Results of this nnet3-am-init exp/dev_clean_ali/final.mdl exp/chain/tdnn1j_sp_online_dev_clean/input.raw - | nnet3-am-train-transitions ....

number of phones 346
number of pdfs 2344
number of transition-ids 26572
number of transition-states 13286

Results of this nnet3-info --print-args=false exp/chain/tdnn1j_sp_online_dev_clean/input.raw | fgrep  ' name=output '

output-node name=output input=output.affine dim=2344 objective=linear

**Comment by kkm000** [comment]
> Results of this `nnet3-am-init exp/dev_clean_ali/final.mdl exp/chain/tdnn1j_sp_online_dev_clean/input.raw - | nnet3-am-train-transitions ....`

But wait, in your initial report nnet3-am-train-transitions dies with an assertion failure. Did you mean the result of `am-info exp/dev_clean_ali/final.mdl` ?

**Comment by kkm000** [comment]
@Asma-droid, friendly ping.

**Comment by kkm000** [comment]
I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!
