### ISSUE TITLE
RNNlm training not rnnlm rescoring

### ISSUE THREAD

**Issue by qkrguswn2401** [kaldi-asr/kaldi#4609]
Hi,  I am aware of building kaldi with ngram and rnnlm rescoring.  What I am trying to do is use rnnlm instead of ngram?  I know how to build rnnlm using kaldi but I don't know how to incorporate rnnlm into kaldi for training, not rescoring.  Based on What I know, RNNlm is used only for rescoring.  I would like to know if there is an example or a script to look at to build rnnlm-based kaldil.  LM needs to be in arpa format.  how do I convert rnnlm into arpa format?  thank you.

**Comment by RuABraun** [comment]
Your question does not make sense.

The arpa format is meant for ngram models. An RNNLM is not an ngram.

**Comment by kkm000** [comment]
I'm closing this issue, because it is a question, not a feature proposal or a defect report. **We have a forum that is the best place to ask questions**, and getting answers and input from other users as well. We are hanging out there all the time, too. Here, in the issue tracker, we are just too few.

**Kaldi help forum**: https://groups.google.com/forum/#!forum/kaldi-help

**Instructions for joining**: http://kaldi-asr.org/forums.html

If you think I misunderstood your intention, please reply, and I'll reopen it.
