### ISSUE TITLE
'nnet3-latgen-faster' takes longer time in the first run compared to later runs

### ISSUE THREAD

**Issue by emirdemirel** [kaldi-asr/kaldi#4630]
Hi, 

I developed a Kaldi speech-to-text module for my research deployed via a Docker image, and I realised that every time I create a new Docker container, the code 'nnet3-latgen-faster' takes a longer time when it is first run, but its runtime gets lower in the later runs. 

Question: Does 'nnet3-latgen-faster' create some cached files in its initial runs which can later be used for later runs? Can this be the reason why the first run takes a longer time?

Thanks in advance

**Comment by danpovey** [comment]
No cached files, but possibly either a docker-related issue or an issue
related to files cached in memory by the OS.

**Comment by kkm000** [comment]
It's your normal page cache at work. When you run a container, an overlay filesystem is mounted. ld.so needs to load a lot of .so libraries from disk, including MKL and other huge stuff when starting a process. Some sections (code, rodata etc) of SO files are mapped into memory as R/O pages backed by the file (so that they simply dropped if kernel needs to swap them out). Even when a SO is no longer referenced, the kernel still keeps the mapped pages opportunistically. When a container is stopped, the overlay filesystem is unmounted and the cached mappings purged, as they are associated to the filesystem inode, and the backing filesystem is now gone.

You can mount /var/lib/docker to a dedicated SSD NVME device to improve its disk performance.

I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!
