### ISSUE TITLE
Full ubm training SRE08 VS SRE10

### ISSUE THREAD

**Issue by StevenLOL** [kaldi-asr/kaldi#477]
In egs/SRE08:

The full UBM is first trained on 8k utterances , then trained on all male/female data.

but in SRE10 V1:

The full UBM is only trained once on 32k utterances.

1) Why not train this full UBM again on all the data?
2) Is it a good idea to train full UBM with lots of data ?

**Comment by david-ryan-snyder** [comment]
@StevenLOL This just reflects two ways of doing roughly the same thing.  In the SRE08 example, we create two separate systems for each gender, and evaluate the male and female portions separately. The SRE10 example focuses on gender-_in_dependent speaker ID. We also evaluate the male and female portions individually, but we do so by creating separate PLDA backends, and share all of the other models. I think using the 32k dataset is probably overkill--less than that should achieve the same results. Probably discussions of this type are best begun on http://kaldi-asr.org/forums.html rather than as issues. 

@danpovey I think we can close this issue.

**Comment by jtrmal** [comment]
OK, closing (despite the fact I'm not Dan :)

**Comment by david-ryan-snyder** [comment]
OK, I forgot you also have that power :-).
