### ISSUE TITLE
Dockerのイメージ作成時にGPGエラーになる

### ISSUE THREAD

**Issue by akihirof0005** [kaldi-asr/kaldi#4872]
[Dockerfile](https://github.com/kaldi-asr/kaldi/blob/master/docker/ubuntu18.04-cuda10.0/Dockerfile)をビルドする際にGPGエラーが発生する。
エラーが発生するシェルスクリプトはこちらで、
https://github.com/kaldi-asr/kaldi/blob/master/tools/extras/install_mkl.sh
19行目で指定されているものです。
`intel_key_url='https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB'`

実際には以下のエラーが発生します。
```
W: GPG error: https://apt.repos.intel.com/mkl all InRelease: The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
E: The repository 'https://apt.repos.intel.com/mkl all InRelease' is not signed.
```

先月末が期限だったようです。
https://community.intel.com/t5/oneAPI-Registration-Download/The-GPG-PUB-KEY-INTEL-SW-PRODUCTS-PUB-expired/m-p/1529173#M6094

私がビルドしたいDockerfileは元になるイメージもすでに配布されていないですが、必要のため、カスタムして利用しています。

**Comment by ryun0suke22** [comment]
GPG key for MKL is now updated. 

community.intel.com/t5/oneAPI-Registration-Download/The-GPG-PUB-KEY-INTEL-SW-PRODUCTS-PUB-expired/m-p/1530383#M6132

**Comment by ryun0suke22** [comment]
You need to add these

```
RUN apt-get install -y gpg
RUN curl -sSL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor -o /usr/share/keyrings/intel-sw-products.gpg
```

**Comment by kkm000** [comment]
The relevant key https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB has promptly expired on 2021-01-01T00:00:00Z, and a new key was added to this keyring about 36 hours later.

@ryun0suke22
> You need to add these before install_mkl.sh

Not quite, the key should no longer mucked with gpg. Starting with Debian 11, maybe even 10, simply drop the “armored” gpg keychain ASCII file as downloaded from http://.../GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB **with the** `.asc` **extension** to `/etc/apt/trusted.d/`. apt(8) has long supported both binary `.gpg` files, and their "armored" format, pure ASCII `.asc` files, which were invented to transmit key material through terminal-like connections that may not be binary-transparent. 

And yeah, the `install_mkl.sh` script should work now, since the key has now been updated. Ping me if you find otherwise.
