### ISSUE TITLE
Is that OK to use Openfst 1.8.1 in Kaldi's latest version?

### ISSUE THREAD

**Issue by Xiao-persol** [kaldi-asr/kaldi#4884]
I am a beginner and I am trying to install Kaldi. When I finished installing Kaldi, I realised that I also needed to install Openfst.
As Openfst version 1.7.2 is bundled in the tools folder of Kaldi, I tried to install it but it failed. Therefore, I installed version 1.8.1 and succeeded.
However, I want to know if it is okay to install a different version of Openfst.
And if I want to change the openfst which is in Kaldi's tools folder to a newer version, would this affect Kaldi.
Could someone please help me on this? Thanks in advance!

**Comment by danpovey** [comment]
Can you explain how it failed?  Without details it's hard to know whether
it was even OpenFST related.
I am actually surprised you were able to install using OpenFST version
1.8.1, because there are incompatibilities
in the code.
Likely you installed OpenFST in system space, and Kaldi was picking up the
1.7.2 version installed in kaldi/tools/.
See this
https://github.com/kaldi-asr/kaldi/pull/4716
... we are not upgrading to 1.8.1 because it's not possible to upgrade
Kaldi's code to support that OpenFST version
without breaking existing builds, and there was no compelling version to
upgrade.

**Comment by Xiao-persol** [comment]
@danpovey Thanks for the reply, now I know there are incompatibilities between 1.8.1 and 1.7.2.
And as you said, I had OpenFST installed in system space, not actually installed in Kaldi.
But the reason I was trying to install openfst1.8.1 was that I could not successfully #make openfst-1.7.2 by using python3.9.

I think there might be something wrong with my python version. Anyway, thanks again!

**Comment by danpovey** [comment]
I wasn't aware that the OpenFST build script had any dependencies on python.
Until I see concrete output from the screen I cannot really start to help.

**Comment by jtrmal** [comment]
kaldi can now compile and run on 1.8.x openfst, this probably resolves this.
