### ISSUE TITLE
About the implementation of toolkits to retrieve any time-aligned information typically use in research and industry

### ISSUE THREAD

**Issue by a2d8a4v** [kaldi-asr/kaldi#4923]
Hi,

Is it advisable to implement useful toolkits to retrieve time-aligned information, such as suprasegmental, segmental information, or any features stemming from alignment information?

For instance, [fac-via-ppg](https://github.com/guanlongzhao/fac-via-ppg) implements the process of obtaining phonetic posteriorgrams via the [PyKaldi](https://github.com/pykaldi/pykaldi) API, which can be converted to C++ code and ultimately becomes compute-ppg. However, I am concerned that these toolkits may not be compatible with existing Kaldi recipes. I would like to know if it is better to merge these codes into Kaldi or create an independent repository.

Best regards,

**Comment by kkm000** [comment]
I'm not really sure that I copy you, but since you can use the Kaldi API exposed via Python wrapper, you can also link directly against the Kaldi libraries required for your project. Generally, every directory with code whose name does _not_ end in `bin` contains code for a library. Header files are in the same directories as the source files. This is how we productize Kaldi-based speech recognition solutions. You may build either static (.a) or dynamic (.so) libraries. In the latter case, don't forget the OpenFST libraries, built under tools/openfst.

Check the Makefile for libraries interdependency information. Generally, training-time and inference-time libraries are separate, but there is some lumping in the nnet2 and nnet3 libraries.

Is this something that you want to achieve?

**Comment by a2d8a4v** [comment]
Hi @kkm000,

I mean, I'm not sure if it's a good idea to implement such toolkits in Kaldi, given that Kaldi is specifically designed for automatic speech recognition, keyword spotting, and related tasks. I'm concerned that adding toolkits to retrieve time-aligned information, such as suprasegmental and segmental data, might conflict with the original purpose of Kaldi.

Sincerely,

**Comment by kkm000** [comment]
I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!
