### ISSUE TITLE
get_utt2dur.sh does not seems to work properly for speed-perturbed data

### ISSUE THREAD

**Issue by freewym** [kaldi-asr/kaldi#671]
Hi,

I want to obtain the total duration for a subset. So I tried to use utils/data/get_utt2dur.sh to get the duration of each utterance. It works fine on non-speed-perturbed data. But as to speed-perturb data, the duration for speed-perturbed utterances seem not correct.

E.g., In /home/ywang/kaldi-chain2/egs/librispeech/s5/data/train_960_sp/utt2dur, all utterances prefixed with sp0.9- or sp1.1- have the same duration 67108.73, which does not look correct, while durations of  utterances prefixed with sp1.0-, which correspond to the non-perturbed ones, look reasonable.

I also tried on swbd/s5c/data/train_nodup_sp. get_utt2dur.sh works fine when the file segments is present. But if I removed segments, the script will compute the duration from wav.scp and there also seems to have the same problem for speed-perturbed utterances.

**Comment by danpovey** [comment]
Please sort this out with Vijay.  It's possible that the script that
perturbed the data did not correctly modify the utt2dur, and you're using a
cached version of the utt2dur file.  Getting it from the wav.scp should
work fine- it will go through the speed-perturbing before it's read.
Dan

**Comment by vijayaditya** [comment]
The issue occurs to issue in wav-to-duration.cc. The wav_data.Duration() returns the wrong duration as wav_data_ has the wrong num_cols_.
There seems to be an issue with reading file-length from streaming wav-data.
<code>sox WARN wav: Length in output .wav header will be wrong since can't seek to fix it</code>

**Comment by danpovey** [comment]
Oh.  I think it's probably a bug in sox where, when it runs the
speed-modification command, it outputs the original (un-speed-perturbed)
length.  Sometimes it feels like sox's authors aren't even trying to make
it correct.
We could work around it by ensuring that the script that does the speed
perturbing create the utt2dur files itself- even if they were not present
in the source directory.
Dan

**Comment by vijayaditya** [comment]
OK, this will be a modification in speed-perturbation code then.  @tomkocse / @freewym would you have time to fix this. 

To do:
If there is no segments file in the data directory, before perturbing the data generate an utt2dur file. Create the utt2dur file for perturbed data by modifying the non-perturbed data's utt2dur file.

**Comment by danpovey** [comment]
To avoid problems in the future, it might also be a good idea to add an
option to wav-to-duration like --read-entire-file, which would force it to
use the regular WaveHolder instead of the WaveHeaderHolder (name may be
wrong), and that should ensure that the sizes are correct.  Then the
get_utt2dur.sh can grep in the wav.scp for the relevant sox command, and if
it's present, add the --read-entire-file option and just warn that it's
going to be slow.  Maybe you could get Yiming or someone else to do this.

Dan

**Comment by nshmyrev** [comment]
I've just had a problem today with a data folder without wav, get_utt2dur just breaks on it. It might be perfectly possible to train on such data. I'm not sure how wav duration is relevant to nnet training at all, maybe you can just count features.

**Comment by danpovey** [comment]
Yiming, can you please also modify the script so that if wav.scp is not
present, it will back off to obtaining it from the feats.scp via
feat-to-len-- there can be a frame_shift=0.01 option added to the
get_utt2dur.sh script, which will determine the interpretation of the frame
shift in seconds, only to be used if the wav.scp is not present and we are
getting the durations from the features.

In fact what the neural net training needs is the total duration in frames
of the data.  However, reading all the features to determine this is quite
inefficient, and very often we know it anyway from the segments file.
That's why we get this information from the utt2dur file; the
get_utt2dur.sh script is to provide a central location for the scripts that
get the duration.

Dan

**Comment by freewym** [comment]
OK.
