### ISSUE TITLE
Relevance of model combination stage in chain recipe

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#701]
Remi Francis recently found that the model combination stage is either bit beneficial or even hurtful to the  performance of the AMs trained with chain objfn. We would like to examine this more closely and eliminate this stage from the recipe if necessary.

@pegahgh You had similar observations even with the cross entropy objfn, could you take this up ?

**Comment by pegahgh** [comment]
Yes! I got small performance degradation(0.2% abs) on WSJ using model combination. I can investigate it in more details for chain model.

**Comment by vijayaditya** [comment]
@pegahgh any progress? Could you please keep writing intermediate updates here.

**Comment by pegahgh** [comment]
We recently use two new constraints, positive weights and sum-to-one, in combining chain model. I am worried that sum-to-one constraint will hurt optimization problem. I looked at the weight in model combination and they decay exponentially w.r.t model number and objective function doesn't improve after  2 or 3 iterations. 
I will give some update as soon as I get some results.

**Comment by danpovey** [comment]
Any constraint will hurt the optimization viewed purely as an optimization
problem, but there are reasons for those things... it's basically to have a
more conservative model combination that has less capacity for doing harm.
The sum-to-one constraint is useful because it avoids changing the
magnitudes of parameters, which would cause problems if one were to retrain
the model afterwards.
If the optimization is hurting us *with* the constraints, it's very
unlikely to be helpful *without* the constraints, because without the
constraints it would just change the final model more aggressively.

Dan

**Comment by vijayaditya** [comment]
@pegahgh Any progress ?

**Comment by pegahgh** [comment]
Model combination on SWBD gives 0.1 to 0.3 % WER improvement on SWBD using
chain model.

System               6v(last iteretaion)        6v(model combination)

WER on train_dev(tg)      14.78     14.68

WER on train_dev(fg)      13.58     13.49

WER on eval2000(tg)        17.5      17.2

WER on eval2000(fg)        15.9      15.7

WER on rt03(tg)        17.0      16.9

WER on rt03(fg)        14.8      14.5

**Comment by francisr** [comment]
Do you have results with BLSTMs?

**Comment by vijayaditya** [comment]
@pegahgh Are you investigating the BLSTMs + model combination, if not could you let me know if you plan to do this in the near future ? If not I will close this issue and create a new one to track BLSTMs + model_combination + chain.
