### ISSUE TITLE
Release tarballs on github

### ISSUE THREAD

**Issue by posophe** [kaldi-asr/kaldi#73]
Hi !

I'm working on speech recognition on openSUSE. I need to package Kaldi at first. Do you plan providing release tarballs in github ? It makes maintainer's life so much easier :).

By advance, thanks for your answer.

**Comment by akreal** [comment]
You can get tarball for any commit via GitHub API (https://developer.github.com/v3/repos/contents/#get-archive-link), for example:

https://api.github.com/repos/kaldi-asr/kaldi/tarball/9c257c5a44a474b791788413f1d3633aa17cea8b

BTW, I did some Kaldi packaging for Gentoo, feel free to borrow if find anything useful:
https://github.com/gentoo-science/sci/tree/master/sci-misc/kaldi
I started to create snapshots, but it was before Kaldi moved to GitHub.

**Comment by posophe** [comment]
You're right, of course, but version control is very helpful in a distribution.

**Comment by danpovey** [comment]
We're not planning on releasing tarballs in the near future because it's
not convenient for the way most people work with Kaldi.  Kaldi is a
research and development environment with many parts that's constantly
being updated; it's not a utility that you would likely want at a fixed
version.  I am a little unsure what you mean by "working on speech
recognition on openSUSE"- whether you are working for the openSUSE project,
or what?  And is this a research project or you're developing some kind of
tool or project, and if so which kind?  Kaldi is something you would use to
build a speech recognition solution, but it's not a finished solution.  And
how you'd want to package it (or bits of it) is very different depending
what the applications.
Dan

**Comment by posophe** [comment]
In the end, I hope introducing Sirius in openSUSE Factory, and make openSUSE the first distribution including this kind of solution :) (I have some issues with sphinx actually). Anyway, thanks for your answer. If you agree, it would be great keeping this topic opened for eventually further questions.

Regards.
Benjamin

**Comment by danpovey** [comment]
I think you may underestimate the amount of work it would take to create a
personal-assistant program that was ready for deployment.  In any case,
only the run-time parts of Kaldi would be needed.  This is a project for a
team including experienced members, not just one person.
Dan

**Comment by posophe** [comment]
I don't underestimate the amount of work. The hardest part will be providing a high quality skill of integration of Sirius into the distribution. And I can't just provide parts of Kaldi I need because other maintainers/developers could require the other parts of Kaldi. I don't develop anything, I just package it. You do the hard part of the work, I do the easiest I believe.

**Comment by jtrmal** [comment]
As far as I know, no-one actively tried to compile it with openfst 1.5 -- you can be first who actually tries :) Not sure if the patches prepared for 1.3.4  would still apply cleanly (or if they are still necessary).
Is there some killer feature? 
y.

**Comment by danpovey** [comment]
Closing this issue; wontfix.  More suitable for help forums anyway.

**Comment by posophe** [comment]
I know you've closed the issue. I just want you to know that upstream code of openfst has changed and your patch can't be applied.

**Comment by danpovey** [comment]
OK thanks.  At some point when we upgrade, we'll look into that.
