### ISSUE TITLE
Propose to use CUB C++ header library for CUDA kernels. 

### ISSUE THREAD

**Issue by kangshiyin** [kaldi-asr/kaldi#799]
CUB is a open source project developed by Nvidia. It provides high performnace, portable (across Nvidia GPUs with different compute capabilities) code to simplify the kernel code writing.

https://nvlabs.github.io/cub/

It is a C++ header-only library using New BSD license. 

My question is can we include it in Kaldi? If yes, is a suggested place where we can put it?

Thx.

**Comment by jtrmal** [comment]
I'm closing it, because the question/suggestion does not even make real sense -- there is no benefit including something without doing the real work -- i.e. rewriting the kernels and testing if the performance would get better (and why).  You are free to experiment with it -- please let us know if you find any speedup/improvement.
