### ISSUE TITLE
left-biphone chain model alignments

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#811]
It just occurred to me that when training the left-biphone chain model, it would be interesting to do a pass of SAT training with a left-biphone model, including alignment passes.  This may improve the alignments in the sense of making them more compatible with a left-biphone model, and that may improve the tree.

**Comment by naxingyu** [comment]
taken

**Comment by naxingyu** [comment]
I tried this but didn't help. WER on eval2000 went from 15.9% to 16.1%. 
Here is how I tried.

1. Do SAT training using a modified train_sat.sh which takes external 
tree, a.k.a. a biphone tree. The number of gaussians is 140000. This is 
a smaller number compared with 200000 in the triphone SAT training, 
because the number of pdfs are 6080 and 8829 respectively.

2. Do align_fmllr and align_fmllr_lats to generate new alis and lats.

3. Rebuild the biphone tree using the new alis.

4. Do chain training using the new biphone tree and lats.

在 2016/5/25 5:03, Daniel Povey 写道:

**Comment by danpovey** [comment]
OK, thanks.

**Comment by naxingyu** [comment]
I increased #gauss to 180000. The result of re-SAT is slightly improved, but still not better than the previous biphone system.
on eval2000:
%WER 15.9 | 4459 42989 | 85.9 9.6 4.5 1.8 15.9 51.9 |  biphone_fg
%WER 17.4 | 4459 42989 | 84.7 10.4 4.9 2.1 17.4 54.3 |  biphone_tg
%WER 15.9 | 4459 42989 | 86.0 9.4 4.6 1.9 15.9 52.4 |  sat_fg
%WER 17.2 | 4459 42989 | 84.7 10.3 5.0 1.9 17.2 54.8 |  sat_tg

on train_dev:
%WER 14.22 [ 6999 / 49204, 918 ins, 1800 del, 4281 sub ]  biphone_fg
%WER 15.03 [ 7393 / 49204, 901 ins, 1886 del, 4606 sub ] biphone_tg
%WER 14.25 [ 7010 / 49204, 843 ins, 1917 del, 4250 sub ] sat_fg
%WER 15.13 [ 7445 / 49204, 784 ins, 2159 del, 4502 sub ] sat_tg

**Comment by naxingyu** [comment]
And the results are on tdnn. I can still try blstm.

**Comment by danpovey** [comment]
I wouldn't bother with BLSTM, results have more random variation than with
TDNN, so when you're changing other things, I think it's always best to run
the TDNN experiment.
Dan

**Comment by francisr** [comment]
Could the results be not as good as expected because biphones GMMs don't produce an alignment as good as the triphone ones?
