### ISSUE TITLE
Add subsampling option in model combination phase of nnet3 training

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#847]
In the model combination phase of nnet3 training the idea is to use models from the last epoch. With the use of larger amounts of training data this can turn out to be very significant. The solution here is to subsample the models, as suggested by Dan in the comments. However this subsampling code has to been implemented. This issue has been created to track this implementation.

( @ngoel17 )

```
378     approx_iters_per_epoch_final = num_archives/num_jobs_final
379     # First work out how many iterations we want to combine over in the final
380     # nnet3-combine-fast invocation.  (We may end up subsampling from these if the
381     # number exceeds max_model_combine).  The number we use is:
382     # min(max(max_models_combine, approx_iters_per_epoch_final),
383     #     1/2 * iters_after_last_layer_added)
384     half_iters_after_add_layers = (num_iters - finish_add_layers_iter)/2
385     num_iters_combine = min(max(max_models_combine, approx_iters_per_epoch_final), half_iters_after_add_layers)
```

**Comment by vijayaditya** [comment]
@vimalmanohar Would be able to address this in  #1066  ?

**Comment by danpovey** [comment]
Just a note: the cost here is mainly a cost of I/O, plus the disk-space cost of having to keep the models on disk.  nnet3-combine does not estimate interpolation weights for each and every model if there are many models; it arranges them in blocks and has a weight per block. 
Therefore the maximum number of models we give to nnet3-combine can be fairly large, like 100.  I'd recommend to keep every n'th model, where n is chosen so that the number of models given to nnet3-combine is at least 100; make this configurable, obviously.  [You should probably also keep the model from the very last iteration, even if it's not a multiple of n.]
Then, of course, you can delete the other models  as you go.
