### ISSUE TITLE
[enhancement] Extend queue.pl to trap signals

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#861]
it would be nice to modify queue.pl to trap the signals KILL and TERM, and kill the job that has been submitted before exiting.

**Comment by vijayaditya** [comment]
Another enhancement would be to provide an option for early exit i.e., if one of the  jobs in the array fails the script should kill all the jobs and exit rather than wait till the end and report the percentage of failure.   If this feature is not activated the script should be printing details of the jobs being aborted/exiting with non-zero status as soon as the failure occurs.

This is essential in large chain recipes like ASpIRE and fisher_swbd where the `align.sh`/`make_denlats.sh` jobs run for more than a week and failure of individual jobs is not reported till the end.

**Comment by kkm000** [comment]
Done in #1309
