### ISSUE TITLE
make scripts python 3-compatible by using //

### ISSUE THREAD

**Issue by galv** [kaldi-asr/kaldi#883]
Right now, `steps/nnet3/train_dnn.py` does `cur_minibatch_size = minibatch_size / 2`. This causes a bug when python 3 is used where cur_minibatch_size becomes a floating point value, not an integer. An integer parsing command (I think in C++ code) is later called, and the (e.g.) 128.0 fails to be parsed as the integer 128, causing the program to crash.

The solution is to use `//` instead of '/', which will produce integers in both python2 and python3. I will make a PR for this specific case, but I wanted to raise the issue. I don't know whether our goal is to support both versions of python.

**Comment by danpovey** [comment]
One of the reasons I started using
 from __future__ import print_function
is so that we can eventually support python3 from the same scripts.
This is more of a long-term goal, it's not the case that we'd advertise
that having /usr/bin/env python pointing to python3 is  'currently
supported'.

It would be good if you make a PR for the fix.

Dan
