### ISSUE TITLE
windows debug the exe problem: "missing the pthreadVC2.dll"

### ISSUE THREAD

**Issue by xwyf05** [kaldi-asr/kaldi#930]
Hi,

I searched the problem for a long time, and tried some solutions by google, but failed to fix it. Could someone please give me the guidence?
Below were the description related to the problem...
Problem generated:
1.  I compiled the Kaldi under the guidance of ~/windows/INSTALL.md, and successed to build the compute-kaldi-pitch-feats.
2.  When I tried to debug the command (compute-kaldi-pitch-feats, I have added the arguments to the command arguments by click the properties-->>configuration properties -->>debugging -- >> command arguments), I received the problem "the program can't start because pthreadgc2.dll is missing from your computer "  

If there were something that I did not describe clearly, please give me your advice.
Thanks very much.

Best

**Comment by jtrmal** [comment]
the DLL pthreadVC2.dll is not available on your path. So either modify the
PATH shell variable or copy the DLL to the same directory as the executable
is.
y.

**Comment by xwyf05** [comment]
Thanks for your kindly answer, I have tried the second method, but it did not work....
1.  I copied the dll to my executable directory, it did not work and popping  the problem again
2.  Could you please guide me how to modify the path shell variable? Did the pthreadVC2.dll says the 
~\kaldi\tools\pthreads\Pre-built.2\dll\x64/pthreadVC2.dll?  if it is, I changed the path according the INSTALL.md, and besides, I modify it to the directory, it did not work~ 

Thanks
JT.W

**Comment by xwyf05** [comment]
Oh sorry,

**Comment by jtrmal** [comment]
I don't understand -- is the pthreadgc2.dll or pthreadvc2.dll? You have to
copy the right dll.
Also, AFAIK, the binary in VS is typically run from a different working
directory than the location of the dll.
Anyway, your issues are really connected to the fact that windows either
does not see the dll or for some reason decided it does not like the dll
(either because of the manifest file or some other --- to me unknown ---
reasons.

Trying to run the executable directly from VS adds another layer of
indirection and another layer of possible issues.
What I'd try is to run cmd.exe, switch to the directory with the executable
and try to run if from the cmd. if it will complain about a missing dll and
the dll is not present in the current directory, add it there. Otherwise
the problem is somewhere else.



y.

**Comment by xwyf05** [comment]
Hi, Jtrmal

I am sorry for my spell mistake , it is the phreadVC2.dll, I used the cmd.exe to run the compute-kaldi-pitch-feats, and I add one by one the missing dll, it works...

Thank you for your warmhearted reply...

Best,
JT.W
