### ISSUE TITLE
Pitch tracking

### ISSUE THREAD

**Issue by xwyf05** [kaldi-asr/kaldi#939]
Hi,
I am learning the pitch extraction algorithm and have read the literature:
"a pitch extraction algorithm tuned for automatic speech recognition". 
I am confused with several questions:

1. Did the wave must be resampled, how the pitch affected the recognition if it not be resampled?
I tracked the realization of computed-and-process-kaldi-pitch-feats, and did not found the setting that can cross the resample... the literature said it can be skipped if not needed, but I did not found the way to skip it..

2. Could the pitch can be output every frame not after the whole frames? I found the ---simulate-first-pass-online=true  --frames-per-chunk=10 can setting the calculation window, if it was setting --frames-per-chunk=1, did it means output the pitch every frame? I saw the result very different from the default...

3. I run into a problem, the same setting about compute-and-process-kaldi-pitch-feats, while the last feature is different from windows and linux... 
as the following:
compute-and-process-kaldi-pitch-feats  --sample-frequency=8000  scp:wav.scp ark,t:test.ark

Did there are different default setting between windows and linux? I check it, but did not found it.

Could someone please give me the guidence?

Thanks very much
JT.W
``

**Comment by vijayaditya** [comment]
(+Pegah as she wrote the pitch processing code)

**Comment by danpovey** [comment]
>
>
> > Did the wave must be resampled, how the pitch affected the recognition
> > if it not be resampled?
> > I tracked the realization of computed-and-process-kaldi-pitch-feats,
> > and did not found the setting that can cross the resample... the
> literature
> > said it can be skipped if not needed, but I did not found the way to skip
> > it..
>

We downsample (to  --resample-frequency=4k by default) both for efficiency
in computing autocorrelations, and because it slightly improves the
results.  I advise not to change that.

> Could the pitch can be output every frame not after the whole frames?
> > I found the ---simulate-first-pass-online=true --frames-per-chunk=10 can
> > setting the calculation window, if it was setting --frames-per-chunk=1,
> did
> > it means output the pitch every frame? I saw the result very different
> from
> > the default...


The internal code does support that.  E.g. online2-wav-dump-features uses
that.  [actually it operates from the whole wav file, but the workflow is
the same as if you were were getting the data bit by bit and outputting it
with low latency].  The --simulate-first-pass-online=true setting of
compute-and-process-kaldi-pitch-feats does that too.  You'd have to go into
the code a bit to get an interface that would be usable in a truly online
application.

The algorithm is a kind of Viterbi algorithm [like all pitch trackers] so
the results you get if done online are based on an approximate traceback,
they won't be the same as if you waited till the end of the file.

The frames-per-chunk does affect how many frames are output at a time and
will affect latency and the accuracy of the pitch tracking when done
online.  Also the --max-frames-latency parameter is relevant for latency
(and the tradeoff with accuracy, for online operation).  We don't seem to
be setting that variable in the configs we use, but e.g. setting it to 10
might improve the accuracy, at the expense of latency.  I notice also that
in some of the configs, e.g. egs/tedlium/s5/conf/pitch.conf, we are setting
--nccf-ballast-online=true, which the comment says improves the online
pitch feature extraction.


> I run into a problem, the same setting about
> > compute-and-process-kaldi-pitch-feats, while the last feature is
> different
> > from windows and linux...
> > as the following:
> > compute-and-process-kaldi-pitch-feats --sample-frequency=8000
> > scp:wav.scp ark,t:test.ark
> >
> > Did there are different default setting between windows and linux? I
> check
> > it, but did not found it.
>

Small differences are not that surprising-- the Viterbi algorithm is
comparing different numbers, and different types of machines will have
slightly different matrix libraries leading to different roundoff, so
sometimes it will choose one number over another.

Dan

**Comment by xwyf05** [comment]
Hi, Dan
Thanks for all your kindly reply. 

1. About the item1, if we want to get the mfcc( or plp) + pitch features, did the mfcc feature obtained like pitch?
(I means after resampled the origin audio data then do the mfcc extractation? ) 

2. About the item3, I learned the three-dim results that printed out  to arkfile means:
 **pov-feature, pitch-feature, and delta-pitch-feature**
The difference what I mean is the delta-pitch-feature, and the pov-feature, pitch-feature are same in the two kinds of platform( linux and windows).
And the different were obviously different, like this:
In the windows:                                                       
1_0_0_0_0_0_0_0  [
  -0.0571072 0.6460934 -0.1681084                           
  -0.2354853 0.6560936 0.03269153 
  -0.3175395 0.6566143 -0.0513619 
  -0.2378696 0.6678715 0.05748458 
  -0.2838619 0.6732082 -0.0006690409 

In the Linux:
1_0_0_0_0_0_0_0  [
  -0.0571072 0.6460934 -0.02324463
  -0.2354853 0.6560926 0.01047801
  -0.3175395 0.6566143 0.006959616
  -0.2378697 0.6678705 0.008448794
  -0.2838618 0.6732082 -0.07547209

Thanks again, and hope to get your reply...
Best regards,
JT.W

**Comment by danpovey** [comment]
Please ask on kaldi-help in future (see kaldi-asr.org/forums.html).

>
>    1.
>
>    About the item1, if we want to get the mfcc( or plp) + pitch features,
>    did the mfcc feature obtained like pitch?
>    (I means after resampled the origin audio data then do the mfcc
>    extractation? )
>
>
No.

> About the item3, I learned the three-dim results that printed out to
arkfile means:

>
>    1.
>
>    *pov-feature, pitch-feature, and delta-pitch-feature*
>    The difference what I mean is the delta-pitch-feature, and the
>    pov-feature, pitch-feature are same in the two kinds of platform( linux and
>    windows).
>    And the different were obviously different, like this:
>    In the windows:
>
>    1_0_0_0_0_0_0_0 [
>    -0.0571072 0.6460934 -0.1681084
>
>    -0.2354853 0.6560936 0.03269153
>    -0.3175395 0.6566143 -0.0513619
>    -0.2378696 0.6678715 0.05748458
>    -0.2838619 0.6732082 -0.0006690409
>
> In the Linux:
> 1_0_0_0_0_0_0_0 [
> -0.0571072 0.6460934 -0.02324463
> -0.2354853 0.6560926 0.01047801
> -0.3175395 0.6566143 0.006959616
> -0.2378697 0.6678705 0.008448794
> -0.2838618 0.6732082 -0.07547209
>

If the delta-pitch-feature was different but the pitch feature was
*exactly* the same, then that would be odd.  But since the delta-pitch is
made from differences  between pitch features, it could probably be
explained simply by tiny differences in the pitch feature, which is no
unexpected.

>
>

**Comment by xwyf05** [comment]
Thanks very much.

JT.W

**Comment by xwyf05** [comment]
Hi, Danpovey
About the big difference between windows and kaldi in delta-pitch as follows: 
1_0_0_0_0_0_0_0 [
    -0.0571072 0.6460934 -0.1681084
    -0.2354853 0.6560936 0.03269153
    -0.3175395 0.6566143 -0.0513619
    -0.2378696 0.6678715 0.05748458
    -0.2838619 0.6732082 -0.0006690409

 In the Linux:
 1_0_0_0_0_0_0_0 [
 -0.0571072 0.6460934 -0.02324463
 -0.2354853 0.6560926 0.01047801
 -0.3175395 0.6566143 0.006959616
 -0.2378697 0.6678705 0.008448794
 -0.2838618 0.6732082 -0.07547209

The root cause maybe the RandGauss() function which called rand(), I setting the configure --delta_pitch_noise_stddev = 0, the result were same.

In order to make the pitch more effective, we should used the default setting, am I right?

Thanks,
Jiantao

**Comment by danpovey** [comment]
OK.
The noise was added for a reason, it prevents exact zeros which are hard to
model with Gaussians.
The differences between Linux and Windows  are not a problem.
Dan

**Comment by xwyf05** [comment]
Thanks very much. 

Best,
Jiantao
