### ISSUE TITLE
Weighted sum descriptor

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#943]
During some discussions in the past year we decided to implement weighted sum descriptor
i.e., 
`Sum(alpha, SumDescriptor1, beta, SumDescriptor2)`. The current sum descriptor just supports
`Sum(SumDescriptor1, SumDescriptor2)`.

This descriptor would be useful to implement operations like delta filtering inside the network.

Required : Familiarity with `src/nnet3/*`

**Comment by danpovey** [comment]
Vijay, I just want to point out that this weighted-sum stuff is actually quite hard to implement, due to the way the internals of the compilation process work.  Implementing it in the obvious way would require adding a weight to the Cindex, and this change would spread its tentacles over the entire codebase, make the compilation harder to debug, and slow the compilation process down.

The most feasible way of implementing it that I can see, that would avoid slowing down the core of the compilation process, is to do it by adding a ScalarScaleComponent that would scale its input by a scalar value.  That could of course be used for experiments without further changes.

Then to make it efficient and to avoid using more memory than needed,  an optimization method could be added [see nnet-optimize.h] that would detect situations where a ScalarScaleComponent existed with an input that was just another node, and would optimize out the application of the component, e.g.replacing operations on its output with suitably scaled operations on its input.  [Note: this should be done fairly early in the optimization process, while all matrices still exist and are initialized at the start and deinitialized at the end.]

This would require modifying struct Command to add an extra argument, 'float scale1', which would be used for commands of type `k*Add*`.  By default it would always be 1.0, as it is currently.  Something to be careful of is that I/O for Command needs to be back compatible with computations written before the change.

**Comment by vijayaditya** [comment]
Thanks for the detailed comments. I will start the implementation, as
suggested, this week.

--Vijay

**Comment by vijayaditya** [comment]
As Babel work is done I will restart effort on this issue. However I am using a combination of Permute and BlockAffine components in my case, so I will do this with a low priority.

**Comment by vijayaditya** [comment]
The combination of Permute and BlockAffine components is not fast enough, so I will be implementing this with a higher priority.

**Comment by danpovey** [comment]
Don't underestimate how hard this is-- it's really very hard.  May be easier to optimize the other components.

**Comment by vijayaditya** [comment]
OK, I will explore all the other options before pursuing this.

**Comment by danpovey** [comment]
After thinking about this a bit, I think there is a reasonably practical way to do the weighted sum stuff.

It could be done as an extension of the dim-range-node, so that the dim-range-node gets a scale; and for syntactic sugar, these nodes would be automatically added.  The reason to combine the dim-range and scale operations, rather than have them as separate things, is so that you could combine the dim-range and scale operations without much compilation; and it keeps the compilation simple because the operations behave in a very similar way.

For syntactic sugar, in nnet config files specified by the user these things would be specified using expressions like DimRange(foo, 0, 50), which would automatically add a dim-range node with a specified name, e.g.  foo.dim-range-0-50 [let's say this is interpeted as (offset, dim)].   And the same if you use Scale(foo, 0.5)... a node called foo.scale-0.5 would be added [this would also be a dim-range node, just with a scale that's not 1, and dimensions consisting of everything].  If the user combined these things, like Scale(DimRange(foo, 0, 50), 0.5), we'd probably call it something like foo.dim-range-0-50-scale-0.5.

This is still a lot of work, but it is at least feasible.
