### ISSUE TITLE
bug in get_ctm.sh

### ISSUE THREAD

**Issue by vince62s** [kaldi-asr/kaldi#947]
I think there is a bug in the recent change below
for instance if nj=1 then the second line in bold will become lats=.../lat.{1}.gz
instead of lat.1.gz

```
nj=$(cat $dir/num_jobs)
+  **lats=$(eval echo $dir/lat.{$(seq -s, $nj)}.gz)**
   if [ -f $lang/phones/word_boundary.int ]; then
     $cmd LMWT=$min_lmwt:$max_lmwt $dir/scoring/log/get_ctm.LMWT.log \
       set -o pipefail '&&' mkdir -p $dir/score_LMWT/ '&&' \
-      lattice-1best --lm-scale=LMWT "ark:gunzip -c $dir/lat.*.gz|" ark:- \| \
+      lattice-1best --lm-scale=LMWT "ark:gunzip -c $lats|" ark:- \| \
       lattice-align-words $lang/phones/word_boundary.int $model ark:- ark:- \| \
-      nbest-to-ctm --frame-shift=$frame_shift ark:- - \| \
+      nbest-to-ctm --frame-shift=$frame_shift --print-silence=$print_silence ark:- - \| \
       utils/int2sym.pl -f 5 $lang/words.txt \| \
       $filter_cmd '>' $dir/score_LMWT/$name.ctm || exit 1;
-  else
-    if [ ! -f $lang/phones/align_lexicon.int ]; then
-      echo "$0: neither $lang/phones/word_boundary.int nor $lang/phones/align_lexicon.int exists: cannot align."
-      exit 1;
-    fi
-
+  elif [ ! -f $lang/phones/align_lexicon.int ]; then
     $cmd LMWT=$min_lmwt:$max_lmwt $dir/scoring/log/get_ctm.LMWT.log \
       set -o pipefail '&&' mkdir -p $dir/score_LMWT/ '&&' \
-      lattice-1best --lm-scale=LMWT "ark:gunzip -c $dir/lat.*.gz|" ark:- \| \
+      lattice-1best --lm-scale=LMWT "ark:gunzip -c $lats|" ark:- \| \
       lattice-align-words-lexicon $lang/phones/align_lexicon.int $model ark:- ark:- \| \
-      nbest-to-ctm --frame-shift=$frame_shift ark:- - \| \
+      nbest-to-ctm --frame-shift=$frame_shift --print-silence=$print_silence ark:- - \| \
       utils/int2sym.pl -f 5 $lang/words.txt \| \
       $filter_cmd '>' $dir/score_LMWT/$name.ctm || exit 1;
+  else
+    echo "$0: neither $lang/phones/word_boundary.int nor $lang/phones/align_lexicon.int exists: cannot align."
+    exit 1;

```

**Comment by danpovey** [comment]
Hm.  This problem will exist whenever we use the 'seq -s,' mechanism
for this type of purpose, which is in quite a few places.
We avoid expanding with asterisk because (a) it messes up the order of
the lattices if there are more than 9, and (b) it's dangerous if you
rerun with a smaller number of jobs.
We were considering getting rid of the 'seq -s,' mechanism anyway,
because it's incompatible with systems where /bin/sh links to dash
(i.e. debian).  The right solution is probably to expand all the
lattice names into a string, like the following:

lats=$(for n in $(seq $nj); do echo $dir/lat.$n.gz)

If you have time to prepare a pull request for this, it would be great.
If the scripts in question test for dash and die, you can remove the test.
Dan

**Comment by danpovey** [comment]
@LvHang, you could prepare a pull request to deal with this issue.  Search in the scripts for 'seq -s,' and for 'dash'.

**Comment by vince62s** [comment]
sorry travelling this week, if not done I'll do this next week.
