### ISSUE TITLE
GPU queue g.q is not documented at http://kaldi-asr.org/doc/queue.html

### ISSUE THREAD

**Issue by Invisibility** [kaldi-asr/kaldi#959]
Hi folks,

I followed the documentation at http://kaldi-asr.org/doc/queue.html to set up grid engine and ran the librispeech recipe with GPU enabled. The execution failed at the point when a job with gpu=1 is queued by steps/nnet2/train_pnorm_fast.sh. This happened because the g.q queue wasn't created. I resolved this issue by creating the g.q, in addition to the all.q.

Then I noticed that non-GPU job were queued to the g.q, even when there were slots in all.q and there were GPU jobs waiting for slots in g.q. I resolved this by introducing my custom conf/queue.conf, which is similar to the default one except the option gpu=0 line:

```
command qsub -v PATH -cwd -S /bin/bash -j y -l arch=*64*
option mem=* -l mem_free=$0,ram_free=$0
option mem=0          # Do not add anything to qsub_opts
option num_threads=* -pe smp $0
option num_threads=1  # Do not add anything to qsub_opts
option max_jobs_run=* -tc $0
default gpu=0
option gpu=0 -q all.q
option gpu=* -l gpu=$0 -q g.q
```

This way, all non-GPU jobs go to all.q and all GPU jobs go to g.q.

If these are the right things to do, maybe the documentation should be updated.

Thanks!

**Comment by danpovey** [comment]
Hm.  In our cluster we have it set up like this:

cat /var/lib/gridengine/default/common/sge_request

-q all.q

[needs to be done on all submit hosts]

so the default queue is all.q.  That makes the '-q all.q' option
unnecessary on that line [it was causing problems on clusters that were set
up in different ways.]

I don't know that there is a very natural place to put this in the docs,
because we don't actually go into how to create the g.q queue in the
documentation.  If you have time to modify the docs and create a pull
request it would be good, though.
Dan

**Comment by Invisibility** [comment]
Thanks for the answers, Dan. They make sense. I will try to update the docs and create a pull request.

**Comment by Potomac** [comment]
Hello,

the documentation has still not been updated, there is no mention of the "g.q" queue in the section "Setting up GridEngine for use with Kaldi" :  

http://kaldi-asr.org/doc/queue.html

the documentation only tells to create "all.q" queue during the setting of gridengine, which leads to an error when the user will run a GPU training script, because the "g.q" queue will be missing : 

Output of qsub was: Unable to run job: Job was rejected because job requests unknown queue "g.q"
Exiting.

**Comment by danpovey** [comment]
The scripts have been set up so that by default they work on our cluster,
but that g.q is not something that's needed for general-purpose use.
Create the config file conf/queue.conf and remove the "-q g.q" from the
default.  Look inside queue.pl for what the default config file looks like.
