### ISSUE TITLE
utt2comb file in data directories to keep track of utterance combinations

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#979]
In the latest chain recipes with mininum segment length constraint the utterances are combined after feature extraction stage. We could maintain an utt2comb file in these data directories, which maps each new utterance to the original utterance ids, so when we perform these operations on other data directories we can **ensure** that the same utterance combinations are done.

**Comment by danpovey** [comment]
I think I made sure the process is basically deterministic.  In any case if
there are small differences, they will just lead to a small subset of
utterances having different id's and/or lengths, and and when any
operations are done across data dirs, this will just lead to a very small
number of utterances not being included in teh computation.  I don't want
to add the utt2comb file because it just adds one more thing to worry about
in the data-dir.

Dan

**Comment by vijayaditya** [comment]
OK, got it.
